# -*- coding: utf-8 -*-
"""SiteLens 自建指纹库（精编版）：类别 + 200+ 条技术指纹。

用 Python 字面量而非 JSON：语法由解释器保证，导入器直接写 PostgreSQL。
规则字段 -> 检测器对应关系见 detectors/base.py：
    headers  响应头    cookies  Cookie    meta  <meta>
    html     HTML正则/dom选择器    scripts  脚本src/内联JS
"""

# (id, 中文名, 图标) —— 顺序即宽表 CSV 导出的列序
CATEGORIES = [
    ("cms", "内容管理系统（CMS）", "layout"),
    ("dashboard", "信息板", "gauge"),
    ("db-manager", "数据库管理器", "database"),
    ("doc-tool", "文档工具", "file-text"),
    ("widget", "微件（Widgets）", "puzzle"),
    ("ecommerce", "电子商务", "shopping-cart"),
    ("gallery", "图库", "image"),
    ("wiki", "维基", "book-open"),
    ("host-panel", "主机面板", "server-cog"),
    ("analytics", "分析", "bar-chart"),
    ("blog", "博客", "pen-line"),
    ("js-framework", "JavaScript 框架", "braces"),
    ("issue-tracker", "问题跟踪器", "circle-dot"),
    ("video-player", "视频播放器", "play"),
    ("comment", "评论系统", "message-square"),
    ("security", "安全", "shield"),
    ("font-script", "字体脚本", "type"),
    ("web-framework", "Web 框架", "layers"),
    ("misc", "杂项", "box"),
    ("editor", "编辑器", "code"),
    ("lms", "学习管理系统（LMS）", "graduation-cap"),
    ("web-server", "Web 服务器", "server"),
    ("cache", "缓存", "zap"),
    ("rich-editor", "富文本编辑器", "text"),
    ("js-graphics", "JavaScript 图形", "pie-chart"),
    ("mobile-framework", "移动框架", "smartphone"),
    ("programming-language", "编程语言", "terminal"),
    ("search-engine", "站内搜索", "search"),
    ("cdn", "内容分发网络（CDN）", "globe"),
    ("marketing", "营销自动化", "megaphone"),
    ("web-server-ext", "Web 服务器扩展", "puzzle-2"),
    ("database", "数据库", "database-2"),
    ("maps", "地图", "map"),
    ("ad-network", "广告", "speaker"),
    ("media-server", "媒体服务器", "film"),
    ("payment", "支付处理器", "credit-card"),
    ("tag-manager", "标签管理器", "tags"),
    ("dev", "开发", "git-branch"),
    ("static-site", "静态站点生成器", "file-code"),
    ("live-chat", "实时聊天", "message-circle"),
    ("crm", "客户关系管理（CRM）", "users"),
    ("seo", "搜索引擎优化（SEO）", "trending-up"),
    ("reverse-proxy", "反向代理", "arrow-left-right"),
    ("load-balancer", "负载均衡", "scale"),
    ("ui-framework", "用户界面（UI）框架", "panels-top-left"),
    ("js-library", "JavaScript 库", "component"),
    ("hosting", "托管 / 平台即服务（PaaS）", "cloud"),
    ("cookie-compliance", "Cookie 合规", "cookie"),
    ("accessibility", "辅助功能", "accessibility"),
    ("auth", "身份验证", "key-round"),
    ("captcha", "验证码", "shield-check"),
    ("affiliate", "联盟计划", "link"),
    ("scheduling", "预约安排", "calendar"),
    ("survey", "调查问卷", "clipboard-list"),
    ("ab-testing", "A/B 测试", "split"),
    ("email", "电子邮件（营销）", "mail"),
    ("remarketing", "再营销", "repeat"),
    ("rum", "真实用户监控（RUM）", "activity"),
    ("social", "社交媒体组件", "share-2"),
    ("browser-fingerprint", "浏览器指纹识别", "fingerprint"),
    ("onboarding", "用户引导", "mouse-pointer-click"),
    ("performance", "性能", "timer"),
    ("feature-mgmt", "功能管理", "toggle-right"),
    ("translation", "翻译", "languages"),
    ("reviews", "评价", "star"),
    ("form-builder", "表单构建器", "text-cursor-input"),
    ("fundraising", "募款与捐赠", "heart"),
    ("ticketing", "票务预订", "ticket"),
    ("livestream", "直播", "radio"),
    ("crypto-miner", "加密货币挖矿器", "coins"),
    ("site-builder", "网页构建器", "layout-dashboard"),
    ("icon-lib", "图标库", "shapes"),
    ("oa", "办公系统（OA）", "briefcase"),
    ("waf", "防火墙 / WAF", "shield-half"),
    ("camera", "视频监控", "cctv"),
    ("network-device", "网络设备", "router"),
    ("middleware", "中间件", "boxes"),
    ("devops", "研发运维", "infinity"),
]

FINGERPRINTS = [
    # ---------------- CMS / 建站 ----------------
    {"name": "WordPress", "cats": ["cms"], "conf": 100, "website": "https://wordpress.org",
     "rules": {"meta": {"generator": r"WordPress\s*([\d.]+)?"},
               "html": {"html": [r"wp-content", r"wp-includes"], "dom": ["#wpadminbar", "[class*='wp-block-']"]}}},
    {"name": "Drupal", "cats": ["cms"], "conf": 95, "website": "https://www.drupal.org",
     "rules": {"meta": {"generator": r"Drupal\s*([\d.]+)?"},
               "html": {"html": ["/sites/default/files", r"drupal\.js", r"Drupal\.settings"]}}},
    {"name": "Joomla", "cats": ["cms"], "conf": 95, "website": "https://www.joomla.org",
     "rules": {"meta": {"generator": r"Joomla!\s*([\d.]+)?"},
               "html": {"html": ["/media/jui/", "/components/com_"]}}},
    {"name": "Ghost", "cats": ["cms", "blog"], "conf": 90, "website": "https://ghost.org",
     "rules": {"html": {"html": ["ghost-sdk", "content_api_key"], "dom": ["#ghost-portal", ".gh-canvas"]}}},
    {"name": "Typecho", "cats": ["cms", "blog"], "conf": 90, "website": "https://typecho.org",
     "rules": {"cookies": [r"^__typecho"], "html": {"html": ["/usr/themes/", "typecho"]}}},
    {"name": "Halo", "cats": ["cms", "blog"], "conf": 85, "website": "https://www.halo.run",
     "rules": {"html": {"html": ["/themes/[^\"]*halo", "halo-comment"]}}},
    {"name": "DedeCMS", "cats": ["cms"], "conf": 90, "website": "https://www.dedecms.com",
     "rules": {"html": {"html": ["/plus/list\\.php", "/templets/", "dedeajax"]}}},
    {"name": "TYPO3", "cats": ["cms"], "conf": 95, "website": "https://typo3.org",
     "rules": {"html": {"html": ["typo3conf", "typo3temp"]}}},
    {"name": "Craft CMS", "cats": ["cms"], "conf": 85, "website": "https://craftcms.com",
     "rules": {"cookies": [r"^CraftSessionId"], "html": {"html": ["/cpresources"]}}},
    {"name": "Umbraco", "cats": ["cms"], "conf": 90, "website": "https://umbraco.com",
     "rules": {"html": {"html": ["/umbraco/"]}}},
    {"name": "Strapi", "cats": ["cms"], "conf": 60, "website": "https://strapi.io",
     "rules": {"scripts": {"src": [r"strapi\."]}}},
    {"name": "Contentful", "cats": ["cms"], "conf": 80, "website": "https://www.contentful.com",
     "rules": {"scripts": {"src": [r"contentful"]}}},
    {"name": "Wix", "cats": ["site-builder", "cms"], "conf": 95, "website": "https://www.wix.com",
     "rules": {"html": {"html": [r"wixstatic\.com", r"wix\.com"]}}},
    {"name": "Squarespace", "cats": ["site-builder", "cms"], "conf": 95, "website": "https://www.squarespace.com",
     "rules": {"html": {"html": [r"squarespace"]}}},
    {"name": "Webflow", "cats": ["site-builder"], "conf": 95, "website": "https://webflow.com",
     "rules": {"html": {"html": [r"webflow\.(com|io)", "w-nav"]}}},
    # ---------------- 博客 / 静态站点 ----------------
    {"name": "Hexo", "cats": ["blog", "static-site"], "conf": 90, "website": "https://hexo.io",
     "rules": {"meta": {"generator": r"Hexo\s*([\d.]+)?"}, "html": {"html": ["hexo"]}}},
    {"name": "Hugo", "cats": ["blog", "static-site"], "conf": 90, "website": "https://gohugo.io",
     "rules": {"meta": {"generator": r"Hugo\s*([\d.]+)?"}, "html": {"html": [r"powered by Hugo|hugo\.io|/hugo-theme"]}}},
    {"name": "Jekyll", "cats": ["blog", "static-site"], "conf": 80, "website": "https://jekyllrb.com",
     "rules": {"html": {"html": [r"generated by jekyll|jekyllrb\.com|jekyll\.min"]}}},
    {"name": "VuePress", "cats": ["blog", "static-site"], "conf": 90, "website": "https://vuepress.vuejs.org",
     "rules": {"html": {"html": ["vuepress"]}}},
    {"name": "VitePress", "cats": ["static-site", "blog"], "conf": 85, "website": "https://vitepress.dev",
     "rules": {"meta": {"generator": "VitePress"}, "html": {"html": ["vp-doc", "VPNavBar"]}}},
    {"name": "Docusaurus", "cats": ["static-site", "blog"], "conf": 95, "website": "https://docusaurus.io",
     "rules": {"html": {"html": ["__docusaurus", "docusaurus"]}}},
    {"name": "11ty (Eleventy)", "cats": ["static-site"], "conf": 85, "website": "https://www.11ty.dev",
     "rules": {"meta": {"generator": "Eleventy"}, "html": {"html": ["11ty"]}}},
    {"name": "MkDocs", "cats": ["static-site", "doc-tool"], "conf": 90, "website": "https://www.mkdocs.org",
     "rules": {"meta": {"generator": "MkDocs"}, "html": {"html": ["mkdocs"]}}},
    # ---------------- 电子商务 ----------------
    {"name": "WooCommerce", "cats": ["ecommerce"], "conf": 100, "website": "https://woocommerce.com",
     "rules": {"html": {"html": ["woocommerce"], "dom": [".woocommerce", ".woocommerce-result-count"]}}},
    {"name": "Shopify", "cats": ["ecommerce"], "conf": 100, "website": "https://www.shopify.com",
     "rules": {"html": {"html": [r"cdn\.shopify\.com", "shopify-features", r"shopify\.com"]}}},
    {"name": "Magento", "cats": ["ecommerce"], "conf": 95, "website": "https://business.adobe.com/products/magento",
     "rules": {"html": {"html": ["Magento", r"/static/version\d+", "mage/cookies"]}}},
    {"name": "PrestaShop", "cats": ["ecommerce"], "conf": 95, "website": "https://www.prestashop.com",
     "rules": {"html": {"html": ["prestashop"]}}},
    {"name": "OpenCart", "cats": ["ecommerce"], "conf": 80, "website": "https://www.opencart.com",
     "rules": {"html": {"html": [r"index\.php\?route="]}}},
    {"name": "Shopware", "cats": ["ecommerce"], "conf": 90, "website": "https://www.shopware.com",
     "rules": {"html": {"html": ["shopware"]}}},
    {"name": "BigCommerce", "cats": ["ecommerce"], "conf": 95, "website": "https://www.bigcommerce.com",
     "rules": {"html": {"html": ["bigcommerce"]}}},
    {"name": "有赞", "cats": ["ecommerce"], "conf": 90, "website": "https://www.youzan.com",
     "rules": {"scripts": {"src": [r"yzcdn\.cn|youzan"]}}},
    {"name": "ECShop", "cats": ["ecommerce"], "conf": 80, "website": "http://www.ecshop.com",
     "rules": {"html": {"html": ["ECShop"]}}},
    # ---------------- 分析 / 统计 ----------------
    {"name": "Google Analytics", "cats": ["analytics"], "conf": 100, "website": "https://analytics.google.com",
     "rules": {"scripts": {"src": [r"google-analytics\.com", r"googletagmanager\.com/gtag/js", r"G-[A-Z0-9]+"],
                           "content": [r"gtag\('config'", r"ga\('create'", "GoogleAnalyticsObject"]}}},
    {"name": "Microsoft Clarity", "cats": ["analytics", "rum"], "conf": 100, "website": "https://clarity.microsoft.com",
     "rules": {"scripts": {"src": [r"clarity\.ms"], "content": [r"clarity\(\"(up)?load\"|window\.clarity"]}}},
    {"name": "百度统计", "cats": ["analytics"], "conf": 100, "website": "https://tongji.baidu.com",
     "rules": {"scripts": {"src": [r"hm\.baidu\.com"]}}},
    {"name": "友盟+", "cats": ["analytics"], "conf": 95, "website": "https://www.umeng.com",
     "rules": {"scripts": {"src": [r"umeng"]}}},
    {"name": "CNZZ", "cats": ["analytics"], "conf": 95, "website": "https://www.umeng.com",
     "rules": {"scripts": {"src": [r"cnzz"]}}},
    {"name": "51.LA", "cats": ["analytics"], "conf": 95, "website": "https://www.51.la",
     "rules": {"scripts": {"src": [r"51\.la"]}}},
    {"name": "Plausible", "cats": ["analytics"], "conf": 100, "website": "https://plausible.io",
     "rules": {"scripts": {"src": [r"plausible\.io"]}}},
    {"name": "Matomo", "cats": ["analytics"], "conf": 100, "website": "https://matomo.org",
     "rules": {"scripts": {"src": [r"matomo\.js|piwik\.js"]}}},
    {"name": "Statcounter", "cats": ["analytics"], "conf": 100, "website": "https://statcounter.com",
     "rules": {"scripts": {"src": [r"statcounter\.com"]}}},
    {"name": "Yandex.Metrica", "cats": ["analytics"], "conf": 100, "website": "https://metrica.yandex.com",
     "rules": {"scripts": {"src": [r"mc\.yandex\.ru"]}}},
    {"name": "Umami", "cats": ["analytics"], "conf": 85, "website": "https://umami.is",
     "rules": {"scripts": {"src": [r"umami\.is|/umami\.js"]}}},
    {"name": "Fathom", "cats": ["analytics"], "conf": 100, "website": "https://usefathom.com",
     "rules": {"scripts": {"src": [r"usefathom\.com"]}}},
    {"name": "GoSquared", "cats": ["analytics"], "conf": 95, "website": "https://www.gosquared.com",
     "rules": {"scripts": {"src": ["gosquared"]}}},
    {"name": "Clicky", "cats": ["analytics"], "conf": 95, "website": "https://clicky.com",
     "rules": {"scripts": {"src": [r"clicky\.com|static\.getclicky"]}}},
    {"name": "Cloudflare Web Analytics", "cats": ["analytics", "performance"], "conf": 95, "website": "https://www.cloudflare.com/web-analytics",
     "rules": {"scripts": {"src": [r"cloudflareinsights\.com"]}}},
    {"name": "Vercel Analytics", "cats": ["analytics"], "conf": 95, "website": "https://vercel.com/analytics",
     "rules": {"scripts": {"src": [r"/_vercel/insights/script\.js"]}}},
    {"name": "PostHog", "cats": ["analytics", "feature-mgmt"], "conf": 90, "website": "https://posthog.com",
     "rules": {"scripts": {"src": [r"posthog\.com"], "content": [r"posthog\.init"]}}},
    # ---------------- 标签管理 ----------------
    {"name": "Google Tag Manager", "cats": ["tag-manager"], "conf": 100, "website": "https://tagmanager.google.com",
     "rules": {"scripts": {"src": [r"googletagmanager\.com/(gtm|ns)\.js"], "content": ["GTM-[A-Z0-9]+"]}}},
    {"name": "Tealium", "cats": ["tag-manager"], "conf": 95, "website": "https://tealium.com",
     "rules": {"scripts": {"src": ["tealium"]}}},
    {"name": "Segment", "cats": ["tag-manager"], "conf": 95, "website": "https://segment.com",
     "rules": {"scripts": {"src": [r"segment\.(com|io)"], "content": [r"analytics\.load"]}}},
    {"name": "Adobe Launch", "cats": ["tag-manager"], "conf": 95, "website": "https://business.adobe.com/products/experience-platform/launch",
     "rules": {"scripts": {"src": [r"adobedtm\.com"]}}},
    # ---------------- JS 框架 ----------------
    {"name": "React", "cats": ["js-framework"], "conf": 85, "website": "https://react.dev",
     "rules": {"html": {"html": ["__reactContainere", "data-reactroot"], "dom": ["[data-reactroot]"]},
               "scripts": {"content": [r"react-dom\.production", "\"react\":\\s*\""]}}},
    {"name": "Vue.js", "cats": ["js-framework"], "conf": 85, "website": "https://vuejs.org",
     "rules": {"scripts": {"src": [r"vue(\.global|\.runtime|\.esm)?(\.min)?\.js|/vue/dist|vue.runtime"],
                           "content": [r"createApp\(|new Vue\(|Vue\.use\("]}}},
    {"name": "Angular", "cats": ["js-framework"], "conf": 95, "website": "https://angular.io",
     "rules": {"html": {"html": ["ng-version="]}}},
    {"name": "Svelte", "cats": ["js-framework"], "conf": 85, "website": "https://svelte.dev",
     "rules": {"html": {"html": [r"svelte-[a-z0-9]{6}"]}}},
    {"name": "Alpine.js", "cats": ["js-framework"], "conf": 90, "website": "https://alpinejs.dev",
     "rules": {"html": {"dom": ["[x-data]", "[x-cloak]"]},
               "scripts": {"src": [r"alpinejs|alpine-(\.min)?\.js|cdn\.alpinejs\.org"]}}},
    {"name": "htmx", "cats": ["js-framework"], "conf": 90, "website": "https://htmx.org",
     "rules": {"html": {"html": [r"hx-get=|hx-post=|hx-target="]}, "scripts": {"src": [r"htmx(\.min)?\.js"]}}},
    {"name": "Ember.js", "cats": ["js-framework"], "conf": 70, "website": "https://emberjs.com",
     "rules": {"html": {"html": ["<div id=\"ember"]}}},
    {"name": "Remix", "cats": ["js-framework"], "conf": 95, "website": "https://remix.run",
     "rules": {"html": {"html": ["__remixContext"]}}},
    {"name": "Astro", "cats": ["js-framework", "static-site"], "conf": 95, "website": "https://astro.build",
     "rules": {"html": {"html": ["astro-island", "astro-"]}}},
    {"name": "Gatsby", "cats": ["js-framework", "static-site"], "conf": 95, "website": "https://www.gatsbyjs.com",
     "rules": {"html": {"dom": ["#gatsby-focus-wrapper"], "html": ["gatsby-image", "___gatsby"]}}},
    {"name": "Next.js", "cats": ["js-framework", "web-framework"], "conf": 100, "website": "https://nextjs.org",
     "rules": {"html": {"html": ["/_next/static", "__NEXT_DATA__", "__next_f"]}}},
    {"name": "Nuxt.js", "cats": ["js-framework", "web-framework"], "conf": 100, "website": "https://nuxt.com",
     "rules": {"html": {"html": ["__NUXT__", "/_nuxt/"]}}},
    # ---------------- JS 库 ----------------
    {"name": "jQuery", "cats": ["js-library"], "conf": 95, "website": "https://jquery.com",
     "rules": {"scripts": {"src": [r"jquery[.-]?([\d.]+)?(\.min)?\.js"],
                           "content": [r"jQuery v([\d.]+)"]}}},
    {"name": "Zepto", "cats": ["js-library"], "conf": 90, "website": "https://zeptojs.com",
     "rules": {"scripts": {"src": [r"zepto(\.min)?\.js"]}}},
    {"name": "Lodash", "cats": ["js-library"], "conf": 90, "website": "https://lodash.com",
     "rules": {"scripts": {"src": [r"lodash(\.min)?\.js"]}}},
    {"name": "Moment.js", "cats": ["js-library"], "conf": 85, "website": "https://momentjs.com",
     "rules": {"scripts": {"src": [r"moment(\.min)?\.js"]}}},
    {"name": "Day.js", "cats": ["js-library"], "conf": 85, "website": "https://day.js.org",
     "rules": {"scripts": {"src": [r"dayjs(\.min)?\.js"]}}},
    {"name": "GSAP", "cats": ["js-library"], "conf": 95, "website": "https://gsap.com",
     "rules": {"scripts": {"src": [r"gsap(\.min)?\.js|TweenMax(\.min)?\.js"]}}},
    {"name": "Swiper", "cats": ["js-library"], "conf": 90, "website": "https://swiperjs.com",
     "rules": {"html": {"html": ["swiper-container|swiper-slide|swiper-wrapper"]}, "scripts": {"src": ["swiper"]}}},
    {"name": "SweetAlert", "cats": ["js-library"], "conf": 90, "website": "https://sweetalert.js.org",
     "rules": {"scripts": {"src": ["sweetalert"]}}},
    {"name": "AOS", "cats": ["js-library"], "conf": 90, "website": "https://michalsnik.github.io/aos",
     "rules": {"html": {"html": ["data-aos="]}, "scripts": {"src": [r"aos(\.min)?\.js"]}}},
    {"name": "Popper", "cats": ["js-library"], "conf": 70, "website": "https://popper.js.org",
     "rules": {"scripts": {"src": [r"popper(\.min)?\.js"]}}},
    # ---------------- UI 框架 ----------------
    {"name": "Bootstrap", "cats": ["ui-framework"], "conf": 85, "website": "https://getbootstrap.com",
     "rules": {"html": {"dom": ["[data-bs-toggle]"], "html": [r"bootstrap(\.min)?\.(css|js)"]},
               "scripts": {"src": [r"bootstrap(\.bundle)?(\.min)?\.js"]}}},
    {"name": "Tailwind CSS", "cats": ["ui-framework"], "conf": 85, "website": "https://tailwindcss.com",
     "rules": {"html": {"html": [r"cdn\.tailwindcss\.com|tailwindcss"]}}},
    {"name": "Bulma", "cats": ["ui-framework"], "conf": 80, "website": "https://bulma.io",
     "rules": {"html": {"html": [r"bulma(\.min)?\.css"]}}},
    {"name": "Element UI / Plus", "cats": ["ui-framework"], "conf": 90, "website": "https://element.eleme.io",
     "rules": {"html": {"html": ["el-button|el-input|element-ui|element-plus"]}}},
    {"name": "Ant Design", "cats": ["ui-framework"], "conf": 85, "website": "https://ant.design",
     "rules": {"html": {"html": ["ant-btn|ant-layout|ant-card"]}}},
    {"name": "Arco Design", "cats": ["ui-framework"], "conf": 80, "website": "https://arco.design",
     "rules": {"html": {"html": ["arco-design|arco-icon"]}}},
    {"name": "Material UI", "cats": ["ui-framework"], "conf": 75, "website": "https://mui.com",
     "rules": {"html": {"html": ["MuiBox|mui-box|material-ui"]}}},
    {"name": "Vuetify", "cats": ["ui-framework"], "conf": 85, "website": "https://vuetifyjs.com",
     "rules": {"html": {"html": ["v-application|v-btn|v-toolbar"]}}},
    {"name": "Radix UI", "cats": ["ui-framework"], "conf": 85, "website": "https://www.radix-ui.com",
     "rules": {"html": {"dom": ["[data-radix-popper-content-wrapper]"], "html": ["data-radix-collection-item"]}}},
    {"name": "Semantic UI", "cats": ["ui-framework"], "conf": 70, "website": "https://semantic-ui.com",
     "rules": {"html": {"html": [r"semantic(\.min)?\.(css|js)"]}}},
    {"name": "UIKit", "cats": ["ui-framework"], "conf": 80, "website": "https://getuikit.com",
     "rules": {"html": {"html": [r"uikit(\.min)?\.(css|js)"]}}},
    {"name": "Foundation", "cats": ["ui-framework"], "conf": 75, "website": "https://get.foundation",
     "rules": {"html": {"html": [r"foundation(\.min)?\.(css|js)"]}}},
    # ---------------- 字体 / 图标 ----------------
    {"name": "Google Font API", "cats": ["font-script"], "conf": 95, "website": "https://fonts.google.com",
     "rules": {"html": {"html": [r"fonts\.googleapis\.com", r"fonts\.gstatic\.com"]}}},
    {"name": "Adobe Fonts", "cats": ["font-script"], "conf": 95, "website": "https://fonts.adobe.com",
     "rules": {"html": {"html": [r"use\.typekit\.net"]}}},
    {"name": "iconfont（阿里）", "cats": ["font-script", "icon-lib"], "conf": 85, "website": "https://www.iconfont.cn",
     "rules": {"html": {"html": [r"at\.alicdn\.com/t/font", r"iconfont\.(css|js)"]}}},
    {"name": "Font Awesome", "cats": ["icon-lib"], "conf": 85, "website": "https://fontawesome.com",
     "rules": {"html": {"html": [r"font-?awesome", "fa-(solid|brands|regular)[\" ]"]}}},
    {"name": "Lucide Icons", "cats": ["icon-lib"], "conf": 80, "website": "https://lucide.dev",
     "rules": {"html": {"html": ["lucide lucide-", "lucide-react|lucide-static"]}}},
    {"name": "Tabler Icons", "cats": ["icon-lib"], "conf": 85, "website": "https://tabler.io/icons",
     "rules": {"html": {"html": ["tabler-icons|icon-tabler"]}}},
    {"name": "Material Icons", "cats": ["icon-lib"], "conf": 85, "website": "https://fonts.google.com/icons",
     "rules": {"html": {"html": ["material-icons|material-symbols"]}}},
    {"name": "Ionicons", "cats": ["icon-lib"], "conf": 85, "website": "https://ionic.io/ionicons",
     "rules": {"html": {"html": ["ionicons"]}}},
    {"name": "Remix Icon", "cats": ["icon-lib"], "conf": 75, "website": "https://remixicon.com",
     "rules": {"html": {"html": ["remixicon", "ri-[a-z0-9]+-line"]}}},
    # ---------------- Web 框架 / 语言 ----------------
    {"name": "Django", "cats": ["web-framework"], "conf": 95, "website": "https://www.djangoproject.com",
     "rules": {"cookies": [r"^csrftoken$", r"^django_"], "html": {"html": ["csrfmiddlewaretoken"]}}},
    {"name": "Flask", "cats": ["web-framework"], "conf": 30, "website": "https://flask.palletsprojects.com",
     "rules": {"cookies": [r"^session$"]}},
    {"name": "Laravel", "cats": ["web-framework"], "conf": 90, "website": "https://laravel.com",
     "rules": {"cookies": [r"^XSRF-TOKEN$", "laravel_session"], "html": {"html": ["csrf-token"]}}},
    {"name": "Ruby on Rails", "cats": ["web-framework"], "conf": 90, "website": "https://rubyonrails.org",
     "rules": {"html": {"html": ["authenticity_token", "rails-ujs"]}, "cookies": [r"^_rails"]}},
    {"name": "Express", "cats": ["web-framework"], "conf": 100, "website": "https://expressjs.com",
     "rules": {"headers": {"x-powered-by": ["^Express$"]}}},
    {"name": "Spring", "cats": ["web-framework"], "conf": 80, "website": "https://spring.io",
     "rules": {"headers": {"x-application-context": ["."]}}},
    {"name": "ASP.NET", "cats": ["web-framework", "programming-language"], "conf": 95, "website": "https://dotnet.microsoft.com/apps/aspnet",
     "rules": {"cookies": [r"^ASP.NET_SessionId", r"^\.ASPXAUTH"], "html": {"html": [r"__VIEWSTATE|__doPostBack"]}}},
    {"name": "ThinkPHP", "cats": ["web-framework"], "conf": 80, "website": "https://www.thinkphp.cn",
     "rules": {"cookies": [r"^think_"], "html": {"html": ["thinkphp"]}}},
    {"name": "CodeIgniter", "cats": ["web-framework"], "conf": 85, "website": "https://codeigniter.com",
     "rules": {"cookies": [r"^ci_session"]}},
    {"name": "Livewire", "cats": ["web-framework", "js-framework"], "conf": 90, "website": "https://livewire.laravel.com",
     "rules": {"html": {"dom": ["[wire\\:id]"], "html": ["wire:snapshot"]}}},
    {"name": "PHP", "cats": ["programming-language"], "conf": 95, "website": "https://www.php.net",
     "rules": {"headers": {"x-powered-by": [r"PHP/([\d.]+)"]}, "cookies": [r"^PHPSESSID"]}},
    {"name": "Java", "cats": ["programming-language"], "conf": 75, "website": "https://www.java.com",
     "rules": {"cookies": [r"^JSESSIONID"]}},
    {"name": "Python", "cats": ["programming-language"], "conf": 60, "website": "https://www.python.org",
     "rules": {"headers": {"server": [r"Python/([\d.]+)"], "x-powered-by": [r"Python/([\d.]+)"]}}},
    {"name": "Node.js", "cats": ["programming-language", "web-server"], "conf": 70, "website": "https://nodejs.org",
     "rules": {"headers": {"x-powered-by": [r"(?i)node\.?js"]}}},
    # ---------------- Web 服务器 ----------------
    {"name": "Nginx", "cats": ["web-server"], "conf": 100, "website": "https://nginx.org",
     "rules": {"headers": {"server": [r"nginx(?:/([\d.]+))?"]}}},
    {"name": "Apache", "cats": ["web-server"], "conf": 100, "website": "https://httpd.apache.org",
     "rules": {"headers": {"server": [r"Apache(?:/([\d.]+))?"]}}},
    {"name": "Microsoft IIS", "cats": ["web-server"], "conf": 100, "website": "https://www.iis.net",
     "rules": {"headers": {"server": [r"Microsoft-IIS/([\d.]+)"]}}},
    {"name": "LiteSpeed", "cats": ["web-server"], "conf": 100, "website": "https://www.litespeedtech.com",
     "rules": {"headers": {"server": ["LiteSpeed"]}}},
    {"name": "OpenResty", "cats": ["web-server"], "conf": 100, "website": "https://openresty.org",
     "rules": {"headers": {"server": [r"openresty(?:/([\d.]+))?"]}}},
    {"name": "Caddy", "cats": ["web-server"], "conf": 100, "website": "https://caddyserver.com",
     "rules": {"headers": {"server": ["^Caddy$"]}}},
    {"name": "Tengine", "cats": ["web-server"], "conf": 100, "website": "https://tengine.taobao.org",
     "rules": {"headers": {"server": [r"tengine(?:/([\d.]+))?"]}}},
    {"name": "Apache Tomcat", "cats": ["web-server"], "conf": 90, "website": "https://tomcat.apache.org",
     "rules": {"headers": {"server": ["Coyote|Tomcat"]}}},
    {"name": "Kestrel", "cats": ["web-server"], "conf": 100, "website": "https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel",
     "rules": {"headers": {"server": ["Kestrel"]}}},
    {"name": "Gunicorn", "cats": ["web-server"], "conf": 100, "website": "https://gunicorn.org",
     "rules": {"headers": {"server": [r"gunicorn(?:/([\d.]+))?"]}}},
    {"name": "Uvicorn", "cats": ["web-server"], "conf": 100, "website": "https://www.uvicorn.org",
     "rules": {"headers": {"server": ["uvicorn"]}}},
    # ---------------- 服务器扩展 / 缓存 ----------------
    {"name": "ngx_pagespeed", "cats": ["web-server-ext", "performance"], "conf": 100, "website": "https://www.modpagespeed.com",
     "rules": {"headers": {"x-page-speed": ["."], "x-mod-pagespeed": ["."]}}},
    {"name": "Phusion Passenger", "cats": ["web-server-ext"], "conf": 95, "website": "https://www.phusionpassenger.com",
     "rules": {"headers": {"x-powered-by": ["Phusion Passenger"]}}},
    {"name": "Varnish", "cats": ["cache"], "conf": 95, "website": "https://varnish-cache.org",
     "rules": {"headers": {"x-varnish": ["."], "via": ["varnish"]}}},
    {"name": "WP Super Cache", "cats": ["cache"], "conf": 90, "website": "https://wordpress.org/plugins/wp-super-cache",
     "rules": {"html": {"html": ["WP Super Cache|wp-super-cache"]}}},
    {"name": "W3 Total Cache", "cats": ["cache"], "conf": 90, "website": "https://www.boldgrid.com/w3-total-cache",
     "rules": {"html": {"html": ["W3 Total Cache|w3tc"]}}},
    {"name": "WP Rocket", "cats": ["cache"], "conf": 90, "website": "https://wp-rocket.me",
     "rules": {"html": {"html": ["WP Rocket|wp-rocket"]}}},
    {"name": "LiteSpeed Cache", "cats": ["cache"], "conf": 95, "website": "https://www.litespeedtech.com/products/cache",
     "rules": {"headers": {"x-litespeed-cache": ["."], "x-litespeed-vary": ["."]}}},
    {"name": "Squid", "cats": ["cache"], "conf": 90, "website": "http://www.squid-cache.org",
     "rules": {"headers": {"via": ["squid"]}}},
    # ---------------- CDN / 托管 / 代理 ----------------
    {"name": "Cloudflare", "cats": ["cdn", "security"], "conf": 100, "website": "https://www.cloudflare.com",
     "rules": {"headers": {"cf-ray": ["."], "server": ["cloudflare"]}}},
    {"name": "jsDelivr", "cats": ["cdn"], "conf": 95, "website": "https://www.jsdelivr.com",
     "rules": {"html": {"html": [r"cdn\.jsdelivr\.net"]}}},
    {"name": "cdnjs", "cats": ["cdn"], "conf": 95, "website": "https://cdnjs.com",
     "rules": {"html": {"html": [r"cdnjs\.cloudflare\.com"]}}},
    {"name": "unpkg", "cats": ["cdn"], "conf": 95, "website": "https://unpkg.com",
     "rules": {"html": {"html": [r"unpkg\.com"]}}},
    {"name": "BootCDN", "cats": ["cdn"], "conf": 95, "website": "https://www.bootcdn.cn",
     "rules": {"html": {"html": [r"bootcdn\.net|cdn\.bootcss\.com"]}}},
    {"name": "Staticfile CDN", "cats": ["cdn"], "conf": 95, "website": "https://www.staticfile.org",
     "rules": {"html": {"html": [r"staticfile\.org"]}}},
    {"name": "又拍云", "cats": ["cdn"], "conf": 90, "website": "https://www.upyun.com",
     "rules": {"html": {"html": [r"upaiyun\.com|upyun"]}}},
    {"name": "七牛云", "cats": ["cdn"], "conf": 90, "website": "https://www.qiniu.com",
     "rules": {"html": {"html": [r"qiniu(cn|com|kssl|cdn)?\.[-\w.]*|qnssl\.com"]}}},
    {"name": "阿里云 CDN", "cats": ["cdn"], "conf": 90, "website": "https://www.aliyun.com/product/cdn",
     "rules": {"html": {"html": [r"alicdn\.com", r"aliyuncs\.com"]}}},
    {"name": "腾讯云 CDN", "cats": ["cdn"], "conf": 85, "website": "https://cloud.tencent.com/product/cdn",
     "rules": {"html": {"html": [r"myqcloud\.com|idqqimg\.com"]}}},
    {"name": "Akamai", "cats": ["cdn"], "conf": 90, "website": "https://www.akamai.com",
     "rules": {"html": {"html": [r"akamaized\.net|akamaihd\.com"]}, "headers": {"server": ["AkamaiGHost"]}}},
    {"name": "Fastly", "cats": ["cdn"], "conf": 85, "website": "https://www.fastly.com",
     "rules": {"headers": {"x-served-by": [r"cache-[a-z]+\d+"], "x-fastly-request-id": ["."]},
               "html": {"html": ["fastly-insights"]}}},
    {"name": "AWS CloudFront", "cats": ["cdn"], "conf": 95, "website": "https://aws.amazon.com/cloudfront",
     "rules": {"headers": {"x-amz-cf-id": ["."], "via": ["cloudfront"]}}},
    {"name": "Google Cloud Storage", "cats": ["cdn", "hosting"], "conf": 90, "website": "https://cloud.google.com/storage",
     "rules": {"html": {"html": [r"storage\.googleapis\.com"]}}},
    {"name": "KeyCDN", "cats": ["cdn"], "conf": 95, "website": "https://www.keycdn.com",
     "rules": {"headers": {"server": ["keycdn-engine"], "x-cache": [".*keycdn"]}}},
    {"name": "bunny.net", "cats": ["cdn"], "conf": 95, "website": "https://bunny.net",
     "rules": {"html": {"html": [r"b-cdn\.net"]}}},
    {"name": "Vercel", "cats": ["hosting"], "conf": 100, "website": "https://vercel.com",
     "rules": {"headers": {"x-vercel-id": ["."], "x-vercel-cache": ["."]}}},
    {"name": "Netlify", "cats": ["hosting"], "conf": 100, "website": "https://www.netlify.com",
     "rules": {"headers": {"x-nf-request-id": ["."]}}},
    {"name": "GitHub Pages", "cats": ["hosting"], "conf": 95, "website": "https://pages.github.com",
     "rules": {"headers": {"x-github-request-id": ["."]}}},
    {"name": "Heroku", "cats": ["hosting"], "conf": 90, "website": "https://www.heroku.com",
     "rules": {"headers": {"via": [r"1\.1 vegur"]}}},
    {"name": "Render", "cats": ["hosting"], "conf": 95, "website": "https://render.com",
     "rules": {"headers": {"x-render-origin-server": ["."]}}},
    {"name": "Fly.io", "cats": ["hosting"], "conf": 95, "website": "https://fly.io",
     "rules": {"headers": {"fly-request-id": ["."]}}},
    {"name": "AWS S3", "cats": ["hosting"], "conf": 100, "website": "https://aws.amazon.com/s3",
     "rules": {"headers": {"server": ["^AmazonS3$"]}}},
    {"name": "Envoy", "cats": ["reverse-proxy"], "conf": 95, "website": "https://www.envoyproxy.io",
     "rules": {"headers": {"x-envoy-upstream-service-time": ["."], "x-envoy-decorator-operation": ["."]}}},
    {"name": "Traefik", "cats": ["reverse-proxy"], "conf": 90, "website": "https://traefik.io",
     "rules": {"headers": {"server": ["traefik"]}}},
    {"name": "HAProxy", "cats": ["reverse-proxy", "load-balancer"], "conf": 90, "website": "https://www.haproxy.org",
     "rules": {"headers": {"via": ["haproxy"], "server": ["haproxy"]}}},
    {"name": "AWS Elastic Load Balancing", "cats": ["load-balancer"], "conf": 90, "website": "https://aws.amazon.com/elasticloadbalancing",
     "rules": {"headers": {"via": ["awselb"]}}},
    {"name": "Google Cloud Load Balancing", "cats": ["load-balancer"], "conf": 90, "website": "https://cloud.google.com/load-balancing",
     "rules": {"headers": {"via": [r"1\.1 google"]}}},
    {"name": "F5 BIG-IP", "cats": ["load-balancer"], "conf": 95, "website": "https://www.f5.com/products/big-ip-services",
     "rules": {"cookies": [r"^BIGipServer"]}},
    {"name": "Citrix NetScaler", "cats": ["load-balancer"], "conf": 85, "website": "https://www.citrix.com/products/netscaler",
     "rules": {"cookies": [r"^NSC_"]}},
    # ---------------- 支付 ----------------
    {"name": "Stripe", "cats": ["payment"], "conf": 95, "website": "https://stripe.com",
     "rules": {"scripts": {"src": [r"js\.stripe\.com", r"stripe\.com/v3"], "content": [r"Stripe\('[^']+'\)"]}}},
    {"name": "PayPal", "cats": ["payment"], "conf": 95, "website": "https://www.paypal.com",
     "rules": {"scripts": {"src": [r"paypal\.com|paypalobjects\.com"]}}},
    {"name": "支付宝", "cats": ["payment"], "conf": 90, "website": "https://www.alipay.com",
     "rules": {"scripts": {"src": [r"alipayobjects\.com|alipay\.com"], "content": [r"alipay\."]}}},
    {"name": "微信支付", "cats": ["payment"], "conf": 85, "website": "https://pay.weixin.qq.com",
     "rules": {"scripts": {"content": ["WeixinJSBridge|getBrandWCPayRequest|chooseWXPay"]}}},
    {"name": "Square", "cats": ["payment"], "conf": 90, "website": "https://squareup.com",
     "rules": {"scripts": {"src": [r"squareup\.com|squarecdn\.com"]}}},
    {"name": "Braintree", "cats": ["payment"], "conf": 90, "website": "https://www.braintreepayments.com",
     "rules": {"scripts": {"src": [r"braintreegateway\.com|braintree-web"]}}},
    {"name": "Adyen", "cats": ["payment"], "conf": 85, "website": "https://www.adyen.com",
     "rules": {"scripts": {"src": ["adyen"]}}},
    {"name": "Razorpay", "cats": ["payment"], "conf": 95, "website": "https://razorpay.com",
     "rules": {"scripts": {"src": [r"razorpay\.com"]}}},
    {"name": "Paddle", "cats": ["payment"], "conf": 90, "website": "https://www.paddle.com",
     "rules": {"scripts": {"src": [r"paddle\.com"]}}},
    # ---------------- 广告 / 营销 / 再营销 ----------------
    {"name": "Google AdSense", "cats": ["ad-network"], "conf": 95, "website": "https://adsense.google.com",
     "rules": {"scripts": {"src": [r"pagead2\.googlesyndication\.com"], "content": ["adsbygoogle"]}}},
    {"name": "Google Ad Manager", "cats": ["ad-network"], "conf": 90, "website": "https://admanager.google.com",
     "rules": {"scripts": {"src": [r"doubleclick\.net|googletagservices\.com"]}}},
    {"name": "Media.net", "cats": ["ad-network"], "conf": 90, "website": "https://www.media.net",
     "rules": {"scripts": {"src": [r"media\.net/contextual"]}}},
    {"name": "Taboola", "cats": ["ad-network"], "conf": 95, "website": "https://www.taboola.com",
     "rules": {"scripts": {"src": [r"taboola\.com"]}}},
    {"name": "Outbrain", "cats": ["ad-network"], "conf": 95, "website": "https://www.outbrain.com",
     "rules": {"scripts": {"src": [r"outbrain\.com"]}}},
    {"name": "百度联盟", "cats": ["ad-network"], "conf": 95, "website": "https://union.baidu.com",
     "rules": {"scripts": {"src": [r"cpro\.baidu\.com"]}}},
    {"name": "Mailchimp", "cats": ["marketing", "email"], "conf": 90, "website": "https://mailchimp.com",
     "rules": {"scripts": {"src": [r"chimpstatic\.com|list-manage\.com|mailchimp"]}}},
    {"name": "HubSpot", "cats": ["marketing", "crm", "email"], "conf": 95, "website": "https://www.hubspot.com",
     "rules": {"scripts": {"src": [r"hs-scripts\.com|js\.hs-scripts|hsforms\.net|hubspot"]}}},
    {"name": "Klaviyo", "cats": ["marketing", "email"], "conf": 95, "website": "https://www.klaviyo.com",
     "rules": {"scripts": {"src": [r"klaviyo\.com"]}}},
    {"name": "Marketo", "cats": ["marketing", "email"], "conf": 90, "website": "https://business.adobe.com/products/marketo",
     "rules": {"scripts": {"src": [r"marketo\.com|munchkin"]}}},
    {"name": "ActiveCampaign", "cats": ["marketing", "email"], "conf": 85, "website": "https://www.activecampaign.com",
     "rules": {"scripts": {"src": ["activecampaign"]}}},
    {"name": "MailerLite", "cats": ["marketing", "email"], "conf": 90, "website": "https://www.mailerlite.com",
     "rules": {"scripts": {"src": ["mailerlite"]}}},
    {"name": "ConvertKit", "cats": ["marketing", "email"], "conf": 90, "website": "https://convertkit.com",
     "rules": {"scripts": {"src": ["convertkit"]}}},
    {"name": "Facebook Pixel", "cats": ["remarketing", "analytics"], "conf": 95, "website": "https://www.facebook.com/business",
     "rules": {"scripts": {"src": [r"connect\.facebook\.net"], "content": [r"fbq\('init'"]}}},
    {"name": "AdRoll", "cats": ["remarketing"], "conf": 90, "website": "https://www.adroll.com",
     "rules": {"scripts": {"src": ["adroll"]}}},
    {"name": "Google Ads Remarketing", "cats": ["remarketing"], "conf": 85, "website": "https://ads.google.com",
     "rules": {"scripts": {"src": [r"googleadservices\.com|googleads\.g\.doubleclick"],
                           "content": ["google_remarketing_only|conversion_id"]}}},
    # ---------------- SEO ----------------
    {"name": "Yoast SEO", "cats": ["seo"], "conf": 95, "website": "https://yoast.com",
     "rules": {"html": {"html": ["yoast"]}}},
    {"name": "Rank Math", "cats": ["seo"], "conf": 90, "website": "https://rankmath.com",
     "rules": {"html": {"html": ["rank-math|rank_math"]}}},
    {"name": "All in One SEO", "cats": ["seo"], "conf": 90, "website": "https://aioseo.com",
     "rules": {"html": {"html": ["aioseo"]}}},
    {"name": "SEOPress", "cats": ["seo"], "conf": 85, "website": "https://www.seopress.org",
     "rules": {"html": {"html": ["seopress"]}}},
    {"name": "Google 站长验证", "cats": ["seo"], "conf": 95, "website": "https://search.google.com/search-console",
     "rules": {"meta": {"google-site-verification": "."}}},
    {"name": "百度站长验证", "cats": ["seo"], "conf": 95, "website": "https://ziyuan.baidu.com",
     "rules": {"meta": {"baidu-site-verification": "."}}},
    {"name": "360 站长验证", "cats": ["seo"], "conf": 95, "website": "https://zhanzhang.so.com",
     "rules": {"meta": {"360-site-verification": "."}}},
    {"name": "搜狗站长验证", "cats": ["seo"], "conf": 90, "website": "https://zhanzhang.sogou.com",
     "rules": {"meta": {"sogou_site_verification": "."}}},
    {"name": "Bing 站长验证", "cats": ["seo"], "conf": 90, "website": "https://www.bing.com/webmasters",
     "rules": {"meta": {r"msvalidate\.01": "."}}},
    # ---------------- A/B / RUM / 性能 ----------------
    {"name": "Optimizely", "cats": ["ab-testing"], "conf": 95, "website": "https://www.optimizely.com",
     "rules": {"scripts": {"src": ["optimizely"]}}},
    {"name": "VWO", "cats": ["ab-testing"], "conf": 95, "website": "https://vwo.com",
     "rules": {"scripts": {"src": [r"visualwebsiteoptimizer\.com|dev\.visualwebsiteoptimizer"]}}},
    {"name": "Google Optimize", "cats": ["ab-testing"], "conf": 95, "website": "https://optimize.google.com",
     "rules": {"scripts": {"src": [r"googleoptimize\.com"]}}},
    {"name": "AB Tasty", "cats": ["ab-testing"], "conf": 95, "website": "https://www.abtasty.com",
     "rules": {"scripts": {"src": [r"abtasty\.com"]}}},
    {"name": "Crazy Egg", "cats": ["ab-testing", "rum"], "conf": 95, "website": "https://www.crazyegg.com",
     "rules": {"scripts": {"src": [r"crazyegg\.com|ceil\.script"]}}},
    {"name": "Hotjar", "cats": ["rum"], "conf": 95, "website": "https://www.hotjar.com",
     "rules": {"scripts": {"src": [r"hotjar\.com|static\.hotjar"]}}},
    {"name": "FullStory", "cats": ["rum"], "conf": 95, "website": "https://www.fullstory.com",
     "rules": {"scripts": {"src": [r"fullstory\.com|fs\.js"]}}},
    {"name": "LogRocket", "cats": ["rum"], "conf": 95, "website": "https://logrocket.com",
     "rules": {"scripts": {"src": ["logrocket"]}}},
    {"name": "Heap", "cats": ["rum", "analytics"], "conf": 85, "website": "https://heap.io",
     "rules": {"scripts": {"src": [r"heap-io\.js|cdn\.heap\.io"]}}},
    {"name": "Mouseflow", "cats": ["rum"], "conf": 95, "website": "https://mouseflow.com",
     "rules": {"scripts": {"src": [r"mouseflow\.com"]}}},
    {"name": "Datadog RUM", "cats": ["rum", "dev"], "conf": 90, "website": "https://docs.datadoghq.com/real_user_monitoring",
     "rules": {"scripts": {"src": [r"datadoghq\.com|datadoghq-browser"], "content": ["DD_RUM|datadogRum"]}}},
    {"name": "New Relic", "cats": ["performance", "rum"], "conf": 95, "website": "https://newrelic.com",
     "rules": {"scripts": {"src": [r"js-agent\.newrelic\.com|nr-data\.net"], "content": ["NREUM|newrelic"]}}},
    {"name": "LazySizes", "cats": ["performance"], "conf": 90, "website": "https://github.com/aFarkas/lazysizes",
     "rules": {"html": {"html": ["data-srcset|lazyload"]}, "scripts": {"src": ["lazysizes"]}}},
    {"name": "instant.page", "cats": ["performance"], "conf": 90, "website": "https://instant.page",
     "rules": {"scripts": {"src": ["instantpage|instant\\.page"]}}},
    {"name": "quicklink", "cats": ["performance"], "conf": 85, "website": "https://github.com/GoogleChromeLabs/quicklink",
     "rules": {"scripts": {"src": ["quicklink"]}}},
    {"name": "LaunchDarkly", "cats": ["feature-mgmt"], "conf": 90, "website": "https://launchdarkly.com",
     "rules": {"scripts": {"src": ["launchdarkly"]}}},
    {"name": "Flagsmith", "cats": ["feature-mgmt"], "conf": 85, "website": "https://flagsmith.com",
     "rules": {"scripts": {"src": ["flagsmith"]}}},
    # ---------------- 地图 / 视频 / 直播 ----------------
    {"name": "Google Maps", "cats": ["maps"], "conf": 90, "website": "https://maps.google.com",
     "rules": {"html": {"html": [r"maps\.googleapis\.com|maps\.google\.com", "gm-style"]}}},
    {"name": "Leaflet", "cats": ["maps", "js-library"], "conf": 90, "website": "https://leafletjs.com",
     "rules": {"html": {"html": [r"leaflet[.-]|leaflet-container", r"leaflet\.css|leaflet\.js"]}}},
    {"name": "Mapbox", "cats": ["maps"], "conf": 90, "website": "https://www.mapbox.com",
     "rules": {"html": {"html": ["mapbox"]}}},
    {"name": "MapLibre", "cats": ["maps"], "conf": 90, "website": "https://maplibre.org",
     "rules": {"html": {"html": ["maplibre"]}}},
    {"name": "百度地图", "cats": ["maps"], "conf": 95, "website": "https://lbsyun.baidu.com",
     "rules": {"scripts": {"src": [r"api\.map\.baidu\.com"]}}},
    {"name": "高德地图", "cats": ["maps"], "conf": 95, "website": "https://lbs.amap.com",
     "rules": {"scripts": {"src": [r"webapi\.amap\.com|restapi\.amap"]}}},
    {"name": "腾讯地图", "cats": ["maps"], "conf": 95, "website": "https://lbs.qq.com",
     "rules": {"scripts": {"src": [r"map\.qq\.com"]}}},
    {"name": "YouTube", "cats": ["video-player"], "conf": 90, "website": "https://www.youtube.com",
     "rules": {"html": {"html": [r"youtube\.com/embed|youtube-nocookie\.com|yt\.player"]}}},
    {"name": "Vimeo", "cats": ["video-player"], "conf": 85, "website": "https://vimeo.com",
     "rules": {"html": {"html": [r"player\.vimeo\.com|vimeo\.com/video"]}}},
    {"name": "哔哩哔哩", "cats": ["video-player", "livestream"], "conf": 85, "website": "https://www.bilibili.com",
     "rules": {"html": {"html": [r"bilibili\.com|hdslb\.com"]}}},
    {"name": "Video.js", "cats": ["video-player"], "conf": 90, "website": "https://videojs.com",
     "rules": {"html": {"html": ["video-js|videojs"]}}},
    {"name": "Plyr", "cats": ["video-player"], "conf": 85, "website": "https://plyr.io",
     "rules": {"html": {"html": ["plyr"]}}},
    {"name": "JW Player", "cats": ["video-player"], "conf": 90, "website": "https://jwplayer.com",
     "rules": {"html": {"html": ["jwplayer|jw-platform"]}}},
    {"name": "DPlayer", "cats": ["video-player"], "conf": 90, "website": "https://dplayer.js.org",
     "rules": {"html": {"html": ["dplayer"]}}},
    {"name": "Wistia", "cats": ["video-player"], "conf": 90, "website": "https://wistia.com",
     "rules": {"scripts": {"src": [r"wistia\.com|wistia\.net"]}}},
    {"name": "Twitch", "cats": ["livestream"], "conf": 80, "website": "https://www.twitch.tv",
     "rules": {"html": {"html": [r"twitch\.tv|twitch-embed"]}}},
    # ---------------- 客服 / 评论 / 社交 ----------------
    {"name": "Intercom", "cats": ["live-chat", "crm"], "conf": 95, "website": "https://www.intercom.com",
     "rules": {"scripts": {"src": ["intercom", "intercomcdn"]}}},
    {"name": "Crisp", "cats": ["live-chat"], "conf": 95, "website": "https://crisp.chat",
     "rules": {"scripts": {"src": [r"crisp\.chat"]}}},
    {"name": "Tawk.to", "cats": ["live-chat"], "conf": 95, "website": "https://www.tawk.to",
     "rules": {"scripts": {"src": [r"tawk\.to"]}}},
    {"name": "LiveChat", "cats": ["live-chat"], "conf": 95, "website": "https://www.livechat.com",
     "rules": {"scripts": {"src": [r"livechatinc\.com|livechat\.com"]}}},
    {"name": "Zendesk", "cats": ["live-chat"], "conf": 95, "website": "https://www.zendesk.com",
     "rules": {"scripts": {"src": ["zendesk", r"zdassets\.com"]}}},
    {"name": "Drift", "cats": ["live-chat", "marketing"], "conf": 90, "website": "https://www.drift.com",
     "rules": {"scripts": {"src": [r"drift\.com|driftt"]}}},
    {"name": "Tidio", "cats": ["live-chat"], "conf": 95, "website": "https://www.tidio.com",
     "rules": {"scripts": {"src": [r"tidio\.co"]}}},
    {"name": "美洽", "cats": ["live-chat"], "conf": 95, "website": "https://meiqia.com",
     "rules": {"scripts": {"src": [r"meiqia\.com"]}}},
    {"name": "网易七鱼", "cats": ["live-chat"], "conf": 95, "website": "https://qiyu.163.com",
     "rules": {"scripts": {"src": [r"qiyukf\.com"]}}},
    {"name": "Disqus", "cats": ["comment"], "conf": 95, "website": "https://disqus.com",
     "rules": {"scripts": {"src": [r"disqus\.com|disquscdn\.com"]}}},
    {"name": "Gitalk", "cats": ["comment"], "conf": 90, "website": "https://github.com/gitalk/gitalk",
     "rules": {"html": {"html": ["gitalk-container|gitalk\\.css|gitalk\\.min\\.js"]}}},
    {"name": "Valine", "cats": ["comment"], "conf": 85, "website": "https://valine.js.org",
     "rules": {"html": {"html": [r"valine\.(js|css)|unpkg\.com/valine|valine"]}}},
    {"name": "Waline", "cats": ["comment"], "conf": 85, "website": "https://waline.js.org",
     "rules": {"html": {"html": [r"waline\.(js|css)|//waline|cdn\.jsdelivr\.net/gh/waline"]}}},
    {"name": "giscus", "cats": ["comment"], "conf": 95, "website": "https://giscus.app",
     "rules": {"scripts": {"src": [r"giscus\.app"]}}},
    {"name": "utterances", "cats": ["comment"], "conf": 95, "website": "https://utteranc.es",
     "rules": {"scripts": {"src": [r"utteranc\.es"]}}},
    {"name": "畅言", "cats": ["comment"], "conf": 90, "website": "https://changyan.kuaizhan.com",
     "rules": {"scripts": {"src": ["changyan"]}}},
    {"name": "X (Twitter) 组件", "cats": ["social"], "conf": 85, "website": "https://developer.twitter.com",
     "rules": {"html": {"html": [r"platform\.twitter\.com"]}}},
    {"name": "AddThis", "cats": ["social"], "conf": 90, "website": "https://www.addthis.com",
     "rules": {"scripts": {"src": [r"addthis\.com|addthisedge\.com"]}}},
    {"name": "ShareThis", "cats": ["social"], "conf": 90, "website": "https://sharethis.com",
     "rules": {"scripts": {"src": [r"sharethis\.com"]}}},
    {"name": "AddToAny", "cats": ["social"], "conf": 90, "website": "https://www.addtoany.com",
     "rules": {"html": {"html": ["addtoany"]}}},
    # ---------------- 维基 / 图库 / 编辑器 ----------------
    {"name": "MediaWiki", "cats": ["wiki"], "conf": 90, "website": "https://www.mediawiki.org",
     "rules": {"html": {"html": ["wgPageName|/mediawiki/|mediawiki"]}}},
    {"name": "DokuWiki", "cats": ["wiki"], "conf": 90, "website": "https://www.dokuwiki.org",
     "rules": {"html": {"html": ["dokuwiki"]}}},
    {"name": "Confluence", "cats": ["wiki"], "conf": 85, "website": "https://www.atlassian.com/software/confluence",
     "rules": {"html": {"html": ["confluence"]}}},
    {"name": "Wiki.js", "cats": ["wiki"], "conf": 85, "website": "https://js.wiki",
     "rules": {"meta": {"generator": r"wiki\.js"}}},
    {"name": "PhotoSwipe", "cats": ["gallery", "js-library"], "conf": 90, "website": "https://photoswipe.com",
     "rules": {"html": {"html": ["photoswipe"]}}},
    {"name": "fancyBox", "cats": ["gallery"], "conf": 90, "website": "https://fancyapps.com",
     "rules": {"html": {"html": ["fancybox"]}}},
    {"name": "GLightbox", "cats": ["gallery"], "conf": 90, "website": "https://github.com/biati-digital/glightbox",
     "rules": {"html": {"html": ["glightbox"]}}},
    {"name": "Lightbox2", "cats": ["gallery"], "conf": 75, "website": "https://lokeshdhakar.com/projects/lightbox2",
     "rules": {"html": {"html": ["lightbox"]}}},
    {"name": "Monaco Editor", "cats": ["editor"], "conf": 90, "website": "https://microsoft.github.io/monaco-editor",
     "rules": {"html": {"html": ["monaco-editor|monaco-mouse-cursor-text"]}}},
    {"name": "CodeMirror", "cats": ["editor"], "conf": 90, "website": "https://codemirror.net",
     "rules": {"html": {"html": ["codemirror"]}}},
    {"name": "Ace Editor", "cats": ["editor"], "conf": 85, "website": "https://ace.c9.io",
     "rules": {"html": {"html": ["ace_editor|ace-(mode|theme)-|ace\\.js"]}}},
    {"name": "CKEditor", "cats": ["rich-editor"], "conf": 85, "website": "https://ckeditor.com",
     "rules": {"html": {"html": [r"ckeditor[./]|ck-editor"]}}},
    {"name": "TinyMCE", "cats": ["rich-editor"], "conf": 90, "website": "https://www.tiny.cloud",
     "rules": {"html": {"html": ["tinymce"]}}},
    {"name": "Quill", "cats": ["rich-editor"], "conf": 85, "website": "https://quilljs.com",
     "rules": {"html": {"html": ["quill|ql-editor"], "dom": [".ql-editor"]}}},
    {"name": "ProseMirror", "cats": ["rich-editor"], "conf": 85, "website": "https://prosemirror.net",
     "rules": {"html": {"html": ["ProseMirror"], "dom": [".ProseMirror"]}}},
    {"name": "Froala", "cats": ["rich-editor"], "conf": 90, "website": "https://froala.com",
     "rules": {"html": {"html": ["froala"]}}},
    {"name": "Summernote", "cats": ["rich-editor"], "conf": 90, "website": "https://summernote.org",
     "rules": {"html": {"html": ["summernote"]}}},
    {"name": "wangEditor", "cats": ["rich-editor"], "conf": 90, "website": "https://www.wangeditor.com",
     "rules": {"html": {"html": ["wangeditor|w-e-text-container"]}}},
    {"name": "UEditor", "cats": ["rich-editor"], "conf": 90, "website": "https://github.com/fex-team/ueditor",
     "rules": {"html": {"html": ["ueditor"]}}},
    {"name": "Editor.md", "cats": ["rich-editor"], "conf": 90, "website": "https://pandao.github.io/editor.md",
     "rules": {"html": {"html": ["editormd"]}}},
    # ---------------- 图形 / 杂项 ----------------
    {"name": "Chart.js", "cats": ["js-graphics"], "conf": 80, "website": "https://www.chartjs.org",
     "rules": {"html": {"html": [r"chart(\.min)?\.js|Chart\("]}}},
    {"name": "ECharts", "cats": ["js-graphics"], "conf": 90, "website": "https://echarts.apache.org",
     "rules": {"html": {"html": ["echarts"]}}},
    {"name": "D3.js", "cats": ["js-graphics"], "conf": 80, "website": "https://d3js.org",
     "rules": {"html": {"html": [r"d3(\.v\d)?(\.min)?\.js"]}}},
    {"name": "Highcharts", "cats": ["js-graphics"], "conf": 90, "website": "https://www.highcharts.com",
     "rules": {"html": {"html": ["highcharts"]}}},
    {"name": "ApexCharts", "cats": ["js-graphics"], "conf": 90, "website": "https://apexcharts.com",
     "rules": {"html": {"html": ["apexcharts"]}}},
    {"name": "Plotly", "cats": ["js-graphics"], "conf": 90, "website": "https://plotly.com",
     "rules": {"html": {"html": ["plotly"]}}},
    {"name": "Three.js", "cats": ["js-graphics"], "conf": 80, "website": "https://threejs.org",
     "rules": {"html": {"html": [r"three(\.min)?\.js|THREE\.WebGLRenderer"]}}},
    {"name": "Lottie", "cats": ["js-graphics"], "conf": 85, "website": "https://airbnb.io/lottie",
     "rules": {"html": {"html": ["lottie"]}}},
    {"name": "Mermaid", "cats": ["js-graphics"], "conf": 80, "website": "https://mermaid.js.org",
     "rules": {"html": {"html": [r"mermaid(\.min)?\.js|class=\"mermaid\""]}}},
    {"name": "Open Graph", "cats": ["misc"], "conf": 95, "website": "https://ogp.me",
     "rules": {"html": {"html": [r"property=\"og:"]}}},
    {"name": "Twitter Cards", "cats": ["misc"], "conf": 90, "website": "https://developer.twitter.com/cards",
     "rules": {"html": {"html": ["name=\"twitter:card\""]}}},
    {"name": "schema.org", "cats": ["misc", "seo"], "conf": 90, "website": "https://schema.org",
     "rules": {"html": {"html": [r"itemtype=\"https?://schema\.org|application/ld\+json"]}}},
    {"name": "HTTP/3", "cats": ["misc", "performance"], "conf": 90, "website": "https://http3.is",
     "rules": {"headers": {"alt-svc": ["h3"]}}},
    {"name": "PWA", "cats": ["misc"], "conf": 85, "website": "https://web.dev/progressive-web-apps",
     "rules": {"html": {"html": ["rel=\"manifest\"|serviceWorker\\.register|apple-mobile-web-app-capable"]}}},
    # ---------------- 认证 / 验证码 / 安全 ----------------
    {"name": "Auth0", "cats": ["auth"], "conf": 90, "website": "https://auth0.com",
     "rules": {"scripts": {"src": [r"auth0\.com"]}}},
    {"name": "Firebase", "cats": ["auth", "database"], "conf": 85, "website": "https://firebase.google.com",
     "rules": {"scripts": {"src": [r"firebase(js)?\.|firebaseio\.com|firebaseapp\.com"], "content": [r"firebase\.initializeApp|firebaseConfig"]}}},
    {"name": "Supabase", "cats": ["auth", "database"], "conf": 85, "website": "https://supabase.com",
     "rules": {"scripts": {"src": ["supabase"], "content": [r"createClient\(['\"].*supabase"]}}},
    {"name": "Clerk", "cats": ["auth"], "conf": 90, "website": "https://clerk.com",
     "rules": {"scripts": {"src": [r"clerk\.(com|accounts\.dev|telemetry\.dev)"]}}},
    {"name": "Okta", "cats": ["auth"], "conf": 85, "website": "https://www.okta.com",
     "rules": {"scripts": {"src": ["okta", r"oktacdn\.com"]}}},
    {"name": "微信 JS-SDK", "cats": ["auth", "social"], "conf": 90, "website": "https://developers.weixin.qq.com",
     "rules": {"html": {"html": [r"wx\.config\("]}, "scripts": {"src": [r"res\.wx\.qq\.com"]}}},
    {"name": "reCAPTCHA", "cats": ["captcha", "security"], "conf": 95, "website": "https://www.google.com/recaptcha",
     "rules": {"html": {"html": ["g-recaptcha|recaptcha/api"]}}},
    {"name": "hCaptcha", "cats": ["captcha", "security"], "conf": 95, "website": "https://www.hcaptcha.com",
     "rules": {"html": {"html": ["hcaptcha"]}}},
    {"name": "Cloudflare Turnstile", "cats": ["captcha", "security"], "conf": 95, "website": "https://developers.cloudflare.com/turnstile",
     "rules": {"html": {"html": [r"challenges\.cloudflare\.com|cf-turnstile"]}}},
    {"name": "极验", "cats": ["captcha"], "conf": 95, "website": "https://www.geetest.com",
     "rules": {"scripts": {"src": ["geetest"]}}},
    {"name": "腾讯云验证码", "cats": ["captcha"], "conf": 90, "website": "https://cloud.tencent.com/product/captcha",
     "rules": {"scripts": {"src": [r"captcha\.qq\.com|turing\.captcha\.qcloud"]}}},
    {"name": "Imperva", "cats": ["security"], "conf": 95, "website": "https://www.imperva.com",
     "rules": {"cookies": [r"^visid_incap", r"^incap_ses"], "html": {"html": ["_Incapsula_Resource"]}}},
    {"name": "DataDome", "cats": ["security"], "conf": 90, "website": "https://datadome.co",
     "rules": {"cookies": [r"^datadome"], "scripts": {"src": [r"datadome\.co"]}}},
    {"name": "Akamai Bot Manager", "cats": ["security"], "conf": 85, "website": "https://www.akamai.com/products/bot-manager",
     "rules": {"cookies": [r"^_abck", r"^bm_sv"]}},
    {"name": "PerimeterX", "cats": ["security"], "conf": 85, "website": "https://www.perimeterx.com",
     "rules": {"cookies": [r"^_px\d", r"^_pxhd"], "scripts": {"src": [r"perimeterx\.net|px-cdn"]}}},
    {"name": "Cloudflare Bot Management", "cats": ["security"], "conf": 85, "website": "https://developers.cloudflare.com/bots",
     "rules": {"cookies": [r"^__cf_bm"]}},
    # ---------------- Cookie 合规 / 辅助功能 / 翻译 ----------------
    {"name": "CookieYes", "cats": ["cookie-compliance"], "conf": 90, "website": "https://www.cookieyes.com",
     "rules": {"scripts": {"src": ["cookieyes"]}}},
    {"name": "Cookiebot", "cats": ["cookie-compliance"], "conf": 95, "website": "https://www.cookiebot.com",
     "rules": {"scripts": {"src": [r"consent\.cookiebot\.com|cookiebot\.com"]}}},
    {"name": "OneTrust", "cats": ["cookie-compliance"], "conf": 95, "website": "https://www.onetrust.com",
     "rules": {"scripts": {"src": [r"cookielaw\.org|onetrust"]}}},
    {"name": "Osano", "cats": ["cookie-compliance"], "conf": 90, "website": "https://www.osano.com",
     "rules": {"scripts": {"src": [r"osano\.com"]}}},
    {"name": "Complianz", "cats": ["cookie-compliance"], "conf": 85, "website": "https://complianz.io",
     "rules": {"html": {"html": ["cmplz"]}}},
    {"name": "UserWay", "cats": ["accessibility"], "conf": 90, "website": "https://userway.org",
     "rules": {"scripts": {"src": ["userway"]}}},
    {"name": "accessiBe", "cats": ["accessibility"], "conf": 90, "website": "https://accessibe.com",
     "rules": {"scripts": {"src": ["accessibe"]}}},
    {"name": "AudioEye", "cats": ["accessibility"], "conf": 90, "website": "https://www.audioeye.com",
     "rules": {"scripts": {"src": ["audioeye"]}}},
    {"name": "Google Translate", "cats": ["translation"], "conf": 85, "website": "https://translate.google.com",
     "rules": {"html": {"html": [r"translate\.google\.com|googtrans"]}}},
    {"name": "GTranslate", "cats": ["translation"], "conf": 85, "website": "https://gtranslate.io",
     "rules": {"html": {"html": ["gtranslate"]}}},
    {"name": "Weglot", "cats": ["translation"], "conf": 90, "website": "https://weglot.com",
     "rules": {"scripts": {"src": [r"weglot\.com"]}}},
    # ---------------- 搜索 / 开发 / 面板 ----------------
    {"name": "Algolia", "cats": ["search-engine"], "conf": 90, "website": "https://www.algolia.com",
     "rules": {"scripts": {"src": [r"algolianet\.com|algolia\.com|algolianet"], "content": ["algoliasearch"]}}},
    {"name": "Elasticsearch", "cats": ["search-engine", "database"], "conf": 70, "website": "https://www.elastic.co",
     "rules": {"html": {"html": ["elasticpress|elasticsearch"]}}},
    {"name": "Swiftype", "cats": ["search-engine"], "conf": 90, "website": "https://swiftype.com",
     "rules": {"scripts": {"src": ["swiftype"]}}},
    {"name": "Google 站内搜索", "cats": ["search-engine"], "conf": 90, "website": "https://programmablesearchengine.google.com",
     "rules": {"scripts": {"src": [r"cse\.google\.com"]}}},
    {"name": "Meilisearch", "cats": ["search-engine"], "conf": 75, "website": "https://www.meilisearch.com",
     "rules": {"html": {"html": ["meilisearch"]}}},
    {"name": "Sentry", "cats": ["dev"], "conf": 95, "website": "https://sentry.io",
     "rules": {"scripts": {"src": [r"browser\.sentry-cdn\.com|ingest\.sentry\.io|sentry-cdn"],
                           "content": [r"Sentry\.init|Sentry\.captureException"]}}},
    {"name": "Rollbar", "cats": ["dev"], "conf": 90, "website": "https://rollbar.com",
     "rules": {"scripts": {"src": ["rollbar"]}}},
    {"name": "Bugsnag", "cats": ["dev"], "conf": 90, "website": "https://www.bugsnag.com",
     "rules": {"scripts": {"src": ["bugsnag"]}}},
    {"name": "Webpack", "cats": ["dev"], "conf": 55, "website": "https://webpack.js.org",
     "rules": {"html": {"html": ["webpackChunk"]}}},
    {"name": "Grafana", "cats": ["dashboard"], "conf": 90, "website": "https://grafana.com",
     "rules": {"html": {"html": ["grafana"]}}},
    {"name": "Kibana", "cats": ["dashboard"], "conf": 90, "website": "https://www.elastic.co/kibana",
     "rules": {"html": {"html": ["kibana"]}}},
    {"name": "Metabase", "cats": ["dashboard"], "conf": 90, "website": "https://www.metabase.com",
     "rules": {"html": {"html": ["metabase"]}}},
    {"name": "宝塔面板", "cats": ["host-panel"], "conf": 85, "website": "https://www.bt.cn",
     "rules": {"html": {"html": ["BT-Panel|btpanel|btwaf"]}}},
    {"name": "phpMyAdmin", "cats": ["db-manager", "host-panel"], "conf": 85, "website": "https://www.phpmyadmin.net",
     "rules": {"html": {"html": ["phpmyadmin|pma_theme"]}}},
    {"name": "Adminer", "cats": ["db-manager"], "conf": 85, "website": "https://www.adminer.org",
     "rules": {"html": {"html": ["adminer"]}}},
    # ---------------- CRM / 文档 / 微件 / LMS ----------------
    {"name": "Salesforce", "cats": ["crm"], "conf": 85, "website": "https://www.salesforce.com",
     "rules": {"html": {"html": ["salesforce|force\\.com"]}}},
    {"name": "Zoho", "cats": ["crm"], "conf": 85, "website": "https://www.zoho.com",
     "rules": {"scripts": {"src": [r"zoho\.com"]}}},
    {"name": "Pipedrive", "cats": ["crm"], "conf": 85, "website": "https://www.pipedrive.com",
     "rules": {"scripts": {"src": ["pipedrive"]}}},
    {"name": "Notion", "cats": ["doc-tool"], "conf": 85, "website": "https://www.notion.so",
     "rules": {"html": {"html": [r"notion\.so|notion\.site"]}}},
    {"name": "Google 文档嵌入", "cats": ["doc-tool"], "conf": 85, "website": "https://docs.google.com",
     "rules": {"html": {"html": [r"docs\.google\.com"]}}},
    {"name": "语雀", "cats": ["doc-tool"], "conf": 80, "website": "https://www.yuque.com",
     "rules": {"html": {"html": ["yuque"]}}},
    {"name": "SlideShare", "cats": ["doc-tool"], "conf": 85, "website": "https://www.slideshare.net",
     "rules": {"html": {"html": ["slideshare"]}}},
    {"name": "Elfsight", "cats": ["widget"], "conf": 90, "website": "https://elfsight.com",
     "rules": {"scripts": {"src": ["elfsight"]}}},
    {"name": "POWR", "cats": ["widget"], "conf": 90, "website": "https://www.powr.io",
     "rules": {"scripts": {"src": [r"powr\.io"]}}},
    {"name": "Moodle", "cats": ["lms"], "conf": 90, "website": "https://moodle.org",
     "rules": {"html": {"html": ["moodle"]}}},
    {"name": "LearnDash", "cats": ["lms"], "conf": 90, "website": "https://www.learndash.com",
     "rules": {"html": {"html": ["learndash"]}}},
    {"name": "Teachable", "cats": ["lms"], "conf": 85, "website": "https://teachable.com",
     "rules": {"html": {"html": ["teachable"]}}},
    {"name": "Thinkific", "cats": ["lms"], "conf": 85, "website": "https://www.thinkific.com",
     "rules": {"html": {"html": ["thinkific"]}}},
    {"name": "Jira", "cats": ["issue-tracker"], "conf": 70, "website": "https://www.atlassian.com/software/jira",
     "rules": {"html": {"html": ["jira"]}}},
    {"name": "Linear", "cats": ["issue-tracker"], "conf": 80, "website": "https://linear.app",
     "rules": {"html": {"html": [r"linear\.app"]}}},
    # ---------------- 移动 / 媒体 / 预约 / 问卷 ----------------
    {"name": "Framework7", "cats": ["mobile-framework"], "conf": 85, "website": "https://framework7.io",
     "rules": {"html": {"html": ["framework7"]}}},
    {"name": "Ionic", "cats": ["mobile-framework"], "conf": 80, "website": "https://ionicframework.com",
     "rules": {"html": {"html": ["ion-page|ion-content|ionic"]}}},
    {"name": "Jellyfin", "cats": ["media-server"], "conf": 90, "website": "https://jellyfin.org",
     "rules": {"html": {"html": ["jellyfin"]}}},
    {"name": "Emby", "cats": ["media-server"], "conf": 90, "website": "https://emby.media",
     "rules": {"html": {"html": ["emby"]}}},
    {"name": "Plex", "cats": ["media-server"], "conf": 85, "website": "https://www.plex.tv",
     "rules": {"html": {"html": [r"plex\.tv|plexapp\.com", r"plex-media-player|/web/plex"]}}},
    {"name": "Calendly", "cats": ["scheduling"], "conf": 95, "website": "https://calendly.com",
     "rules": {"html": {"html": ["calendly"]}}},
    {"name": "Cal.com", "cats": ["scheduling"], "conf": 90, "website": "https://cal.com",
     "rules": {"html": {"html": [r"cal\.com/embed|app\.cal\.com"]}}},
    {"name": "Setmore", "cats": ["scheduling"], "conf": 90, "website": "https://www.setmore.com",
     "rules": {"scripts": {"src": ["setmore"]}}},
    {"name": "Acuity Scheduling", "cats": ["scheduling"], "conf": 90, "website": "https://acuityscheduling.com",
     "rules": {"scripts": {"src": ["acuityscheduling"]}}},
    {"name": "Typeform", "cats": ["survey", "form-builder"], "conf": 90, "website": "https://www.typeform.com",
     "rules": {"html": {"html": [r"typeform\.com|embed\.typeform"]}}},
    {"name": "Google Forms", "cats": ["survey", "form-builder"], "conf": 90, "website": "https://forms.google.com",
     "rules": {"html": {"html": [r"docs\.google\.com/forms"]}}},
    {"name": "SurveyMonkey", "cats": ["survey"], "conf": 90, "website": "https://www.surveymonkey.com",
     "rules": {"html": {"html": ["surveymonkey"]}}},
    {"name": "问卷星", "cats": ["survey"], "conf": 90, "website": "https://www.wjx.cn",
     "rules": {"html": {"html": [r"wjx\.(cn|top)"]}}},
    {"name": "腾讯问卷", "cats": ["survey"], "conf": 90, "website": "https://wj.qq.com",
     "rules": {"html": {"html": [r"wj\.qq\.com"]}}},
    # ---------------- 其他垂直 ----------------
    {"name": "Trustpilot", "cats": ["reviews"], "conf": 85, "website": "https://www.trustpilot.com",
     "rules": {"html": {"html": ["trustpilot"]}}},
    {"name": "Yotpo", "cats": ["reviews"], "conf": 85, "website": "https://www.yotpo.com",
     "rules": {"scripts": {"src": [r"yotpo\.com"]}}},
    {"name": "Jotform", "cats": ["form-builder"], "conf": 85, "website": "https://www.jotform.com",
     "rules": {"scripts": {"src": ["jotform"]}}},
    {"name": "WPForms", "cats": ["form-builder"], "conf": 85, "website": "https://wpforms.com",
     "rules": {"html": {"html": ["wpforms-container|wpforms"]}}},
    {"name": "Gravity Forms", "cats": ["form-builder"], "conf": 80, "website": "https://www.gravityforms.com",
     "rules": {"html": {"html": ["gform_wrapper|gravityforms"]}}},
    {"name": "Buy Me a Coffee", "cats": ["fundraising"], "conf": 85, "website": "https://www.buymeacoffee.com",
     "rules": {"html": {"html": ["buymeacoffee|bmc-button"]}}},
    {"name": "Ko-fi", "cats": ["fundraising"], "conf": 85, "website": "https://ko-fi.com",
     "rules": {"html": {"html": [r"ko-fi\.com"]}}},
    {"name": "Patreon", "cats": ["fundraising"], "conf": 80, "website": "https://www.patreon.com",
     "rules": {"html": {"html": [r"patreon\.com|patreon\.(js|css)"]}}},
    {"name": "Eventbrite", "cats": ["ticketing"], "conf": 90, "website": "https://www.eventbrite.com",
     "rules": {"scripts": {"src": ["eventbrite"]}}},
    {"name": "FingerprintJS", "cats": ["browser-fingerprint"], "conf": 90, "website": "https://fingerprint.com",
     "rules": {"scripts": {"src": [r"fpjs\.io|fingerprintjs"], "content": [r"FingerprintJS\.load"]}}},
    {"name": "Intro.js", "cats": ["onboarding"], "conf": 90, "website": "https://introjs.com",
     "rules": {"html": {"html": ["introjs|intro-js"]}}},
    {"name": "Driver.js", "cats": ["onboarding"], "conf": 85, "website": "https://driverjs.com",
     "rules": {"html": {"html": ["driver-js|driver\\.js|driver-popover"]}}},
    {"name": "Shepherd.js", "cats": ["onboarding"], "conf": 80, "website": "https://shepherdjs.dev",
     "rules": {"html": {"html": ["shepherd\\.js|shepherd-tour"]}}},
    {"name": "Pendo", "cats": ["onboarding"], "conf": 90, "website": "https://www.pendo.io",
     "rules": {"scripts": {"src": [r"pendo\.io"]}}},
    {"name": "Amazon Associates", "cats": ["affiliate", "ad-network"], "conf": 90, "website": "https://affiliate-program.amazon.com",
     "rules": {"html": {"html": ["amazon-adsystem"]}}},
    {"name": "ShareASale", "cats": ["affiliate"], "conf": 85, "website": "https://www.shareasale.com",
     "rules": {"scripts": {"src": ["shareasale"]}}},
    {"name": "Impact", "cats": ["affiliate"], "conf": 80, "website": "https://impact.com",
     "rules": {"scripts": {"src": [r"impact\.com"]}}},
    {"name": "CoinHive 类挖矿", "cats": ["crypto-miner"], "conf": 95, "website": "",
     "rules": {"scripts": {"src": ["coinhive", "minero\\.cc|cryptoloot|authedweb"],
                           "content": ["CryptoLoot|coinhive"]}}},
    # ---------------- flight/动态注入原文指纹（Next.js RSC 数据流） ----------------
    {"name": "Microsoft Clarity", "cats": ["analytics", "rum"], "conf": 90, "website": "https://clarity.microsoft.com",
     "rules": {"html": {"html": [r"clarity\.ms|clarity\""]},
               "scripts": {"src": [r"clarity\.ms"], "content": [r"clarity\(\"(up)?load\"|window\.clarity"]}}},
    {"name": "Google Tag Manager", "cats": ["tag-manager"], "conf": 85, "website": "https://tagmanager.google.com",
     "rules": {"html": {"html": [r"googletagmanager\.com/gtm\.js|GTM-[A-Z0-9]+"]}}},
    {"name": "Stripe", "cats": ["payment"], "conf": 85, "website": "https://stripe.com",
     "rules": {"html": {"html": [r"js\.stripe\.com"]}}},
    {"name": "Vercel Analytics", "cats": ["analytics"], "conf": 90, "website": "https://vercel.com/analytics",
     "rules": {"html": {"html": [r"/_vercel/insights|/_vercel/speed-insights"]}}},
    {"name": "Framer Motion", "cats": ["js-library"], "conf": 80, "website": "https://motion.dev",
     "rules": {"html": {"html": [r"framer-motion|framerusercontent\.com"]}}},
    {"name": "Tailwind CSS", "cats": ["ui-framework"], "conf": 75, "website": "https://tailwindcss.com",
     "rules": {"html": {"html": [r"cdn\.tailwindcss\.com|tailwindcss"]}}},
]
