// 桌面壳「引擎配置落点」决策（纯函数，无 Electron/fs 依赖，node --test 可测）。
//
// 背景（v3.0.0 实测缺陷）：旧实现把 .sitelens.yml 写进**安装目录**
// （resources\engine）。用管理员装到 D:\Program Files 后该目录只读，
// 首启写配置即 EPERM，引擎起不来：
//     engine failed: Error: EPERM: operation not permitted,
//     open 'D:\Program Files\SiteLens\resources\engine\.sitelens.yml'
//
// 修正原则：**运行期会写的文件一律落在可写目录**（userData），安装目录只读资产。
// 本模块只做「配置放哪、首启用什么内容」的纯决策，文件 IO 留给调用方。

"use strict";
const path = require("path");

const CONFIG_NAME = ".sitelens.yml";
const MARKER = "# generated by SiteLens desktop shell";

// configPath 壳管理的配置文件绝对路径（落在用户数据目录，可写）。
function configPath(userDir) {
  return path.join(userDir, CONFIG_NAME);
}

// legacyConfigPath 旧版落点（安装目录）——仅用于一次性迁移读取。
function legacyConfigPath(engineDir) {
  return path.join(engineDir, CONFIG_NAME);
}

// chooseSeed 决定首启写配置时用哪份内容。
//
// 入参：{ userText, legacyText }
//   userText   —— 用户数据目录里已有的配置文本（不存在传 null/undefined）
//   legacyText —— 旧版放在安装目录的配置文本（不存在传 null/undefined）
//
// 返回：{ text, migrate, source }
//   text    写出的初始内容
//   migrate 是否应把旧内容写回用户目录（旧内容非空且带壳标记时才迁移）
//   source  "user" | "legacy" | "fresh"（排障日志用）
//
// 规则：
//   1. 用户目录已有配置 → 用它，不迁移（用户目录是权威源）。
//   2. 否则安装目录有**带壳标记**的旧配置 → 迁移（保留用户改过的引擎键）。
//   3. 否则全新（仅写壳标记行，受管键由 mergeManaged 补齐）。
//   未带壳标记的旧文件视为开发仓库残留，不继承（避免误吞开发配置）。
function chooseSeed(input) {
  input = input || {};
  const userText = input.userText;
  const legacyText = input.legacyText;

  if (typeof userText === "string" && userText.length > 0) {
    return { text: userText, migrate: false, source: "user" };
  }
  if (typeof legacyText === "string" && legacyText.indexOf(MARKER) >= 0) {
    return { text: legacyText, migrate: true, source: "legacy" };
  }
  return { text: MARKER + "\n", migrate: false, source: "fresh" };
}

// isReadOnlyError 判断写入失败是否属「目录不可写」类（EPERM/EACCES/EROFS）。
// 用于在日志里给出可操作提示，而非把原始错误直接抛给用户。
function isReadOnlyError(err) {
  const code = err && err.code;
  return code === "EPERM" || code === "EACCES" || code === "EROFS";
}

// explainError 把配置写入失败翻译成可操作提示（含落点与建议）。
function explainError(err, cfgPath) {
  if (isReadOnlyError(err)) {
    return "无法写入配置 " + cfgPath + "（" + (err && err.code) +
      "）。该目录不可写——请确认 SiteLens 安装目录未被设为只读，" +
      "或以非管理员方式重装到可写路径。";
  }
  return "配置写入失败：" + (err && err.message ? err.message : String(err));
}


// resolveEngineDir 决定「引擎目录」（含引擎程序与数据载荷）。
//
// 打包运行：resourcesPath/engine（安装器布局）。
// 开发运行（未打包）：**优先仓库根**——仓库根有 data/、web/ 与
//   .sitelens.example.yml，是开发期期望的引擎工作目录（可带 live 数据）；
//   若根目录没有引擎程序，则回退到 desktop/engine/（`npm run engine` 的暂存产物），
//   使「npm run engine && npm start」这条 README 已有流程可用
//   （旧实现只认仓库根，源码启动会报「引擎程序缺失」）。
//
// 入参 hasBin(dir) 为注入的判定函数（保持本模块纯函数、可单测）。
function resolveEngineDir(opts) {
  opts = opts || {};
  const exeName = opts.exeName || "sitelens";
  const hasBin = typeof opts.hasBin === "function" ? opts.hasBin : function () { return false; };
  if (!opts.isDev) {
    return path.join(opts.resourcesPath, "engine");
  }
  const rootDir = path.join(opts.dirname, "..");
  if (hasBin(path.join(rootDir, exeName))) return rootDir;
  const stagedDir = path.join(opts.dirname, "engine");
  if (hasBin(path.join(stagedDir, exeName))) return stagedDir;
  return rootDir; // 两处皆无：保留原语义，交由启动校验报「引擎程序缺失」
}

module.exports = {
  CONFIG_NAME: CONFIG_NAME,
  MARKER: MARKER,
  configPath: configPath,
  resolveEngineDir: resolveEngineDir,
  legacyConfigPath: legacyConfigPath,
  chooseSeed: chooseSeed,
  isReadOnlyError: isReadOnlyError,
  explainError: explainError
};
