// yml-merge 单测：桌面壳配置合并的核心不变量——
// 受管键更新、未受管键/注释/未知键保留、缺失段追加、引号安全。
"use strict";
const test = require("node:test");
const assert = require("node:assert");
const { mergeManaged, readListenValue } = require("../lib/yml-merge.js");

const MARK = "# generated by SiteLens desktop shell";

test("缺失配置：生成全部受管键（标记行由调用方前置）", () => {
  const out = mergeManaged("", {
    web: { listen: "127.0.0.1:5087" },
    store: { data_dir: "C:/Users/u/AppData/Roaming/SiteLens/state" },
    checks: { nuclei_dir: "C:/p/nuclei", plugin_dir: "C:/p/plugins" },
    intel: {
      nvd_path: "C:/d/nvd.json.gz",
      tpl_intel_path: "C:/d/tpl.json.gz",
      technologies_path: "C:/d/go/technologies.json"
    }
  });
  assert.ok(out.includes("listen: \"127.0.0.1:5087\""));
  assert.ok(out.includes('data_dir: "C:/Users/u/AppData/Roaming/SiteLens/state"'));
  assert.ok(out.includes("nuclei_dir:"), "nuclei_dir");
  assert.ok(out.includes("plugin_dir:"), "plugin_dir");
  assert.ok(out.includes("nvd_path:"), "nvd_path");
  assert.ok(out.includes("technologies_path:"), "technologies_path");
});

test("用户保存的键与注释在壳重启后原样保留（P0 回归）", () => {
  const existing = [
    MARK,
    "web:",
    "  listen: \"127.0.0.1:5087\"",
    "  api_token: \"user-secret\"",
    "store:",
    "  data_dir: \"C:/x/state\"",
    "crawler:",
    "  # 用户注释必须活着",
    "  max_pages: 9",
    "  respect_robots: false",
    "scan:",
    "  rate_interval_ms: 250",
    "custom_section:",
    "  my_key: keep-me"
  ].join("\n");
  const out = mergeManaged(existing, {
    web: { listen: "127.0.0.1:6000" },
    store: { data_dir: "C:/x/state" },
    checks: { nuclei_dir: "C:/p/nuclei", plugin_dir: "C:/p/plugins" },
    intel: {
      nvd_path: "C:/d/nvd.json.gz",
      tpl_intel_path: "C:/d/tpl.json.gz",
      technologies_path: "C:/d/go/technologies.json"
    }
  });
  assert.ok(out.includes("listen: \"127.0.0.1:6000\""), "受管端口应更新");
  assert.ok(out.includes("api_token: \"user-secret\""), "用户 token 保留");
  assert.ok(out.includes("max_pages: 9"), "用户爬取设置保留");
  assert.ok(out.includes("respect_robots: false"), "用户开关保留");
  assert.ok(out.includes("# 用户注释必须活着"), "注释保留");
  assert.ok(out.includes("my_key: keep-me"), "未知键保留");
  assert.ok(!out.includes("listen: \"127.0.0.1:5087\""), "旧端口不再出现");
});

test("受管段不存在时整段追加", () => {
  const out = mergeManaged("web:\n  listen: \"127.0.0.1:5087\"\n", {
    web: { listen: "127.0.0.1:5087" },
    store: { data_dir: "C:/x/state" },
    intel: { nvd_path: "C:/d/nvd.json.gz", tpl_intel_path: "C:/d/t.json.gz",
      technologies_path: "C:/d/go/t.json" },
    checks: { nuclei_dir: "C:/p/n", plugin_dir: "C:/p/p" }
  });
  assert.ok(out.includes("store:"), "store 段应追加");
  assert.ok(out.includes("intel:"), "intel 段应追加");
  assert.ok(out.includes("checks:"), "checks 段应追加");
  assert.ok(out.includes("overrides_path") === false);
});

test("路径含空格与反斜杠：双引号 + 正斜杠，YAML 安全", () => {
  const out = mergeManaged("", {
    web: { listen: "127.0.0.1:5087" },
    store: { data_dir: "C:\\Users\\feng qiao\\AppData\\Roaming\\SiteLens\\state" }
  });
  assert.ok(out.includes('data_dir: "C:/Users/feng qiao/AppData/Roaming/SiteLens/state"'));
});

test("readListenValue：引号/无引号/非 loopback/缺失四种形态", () => {
  const q = readListenValue('web:\n  listen: "127.0.0.1:5087"\n');
  assert.ok(q && q.host === "127.0.0.1" && q.port === 5087);
  const uq = readListenValue('web:\n  listen: 127.0.0.1:6000\n');
  assert.ok(uq && uq.host === "127.0.0.1" && uq.port === 6000);
  const lan = readListenValue('web:\n  listen: "0.0.0.0:5087"\n');
  assert.ok(lan && lan.host === "0.0.0.0" && lan.port === 5087);
  assert.strictEqual(readListenValue("web:\n  other: x\n"), null);
  assert.strictEqual(readListenValue(""), null);
});
