// 引擎子进程管理（供桌面壳 main.js 调用）。
//
// 职责：初始化用户数据布局 → 写桌面配置 → 拉起 Go 引擎单二进制 →
// 就绪探测。
//
// 数据布局（最优解：更新/卸载永不伤用户数据）——
//   安装目录（只读资产，随 app 更新整体替换）：
//     sitelens.exe + data/{intel_dump,tpl_intel,nvd_cves}.json.gz
//     + data/go（指纹规则种子）+ data/wordlists + data/affected_ranges.json
//   %APPDATA%\SiteLens（用户数据，跨更新存活）：
//     state/（扫描历史 = store.data_dir）
//     pools/nuclei/（模板池 = checks.nuclei_dir，update-nuclei 在线拉取）
//     plugins/（用户插件 = checks.plugin_dir）
//     data/{nvd_cves,tpl_intel}.json.gz + data/go/（可变情报，update-* 写入）
//
// 子进程安全约定：spawn 首参为纯字面量（相对引擎工作目录解析），
// argv 全部内联字面量；不提供环境变量或配置选择可执行程序的通道。
const { app } = require('electron');
const { spawn } = require('child_process');
const fs = require('fs');
const http = require('http');
const net = require('net');
const path = require('path');

const isDev = !app.isPackaged;
const ENGINE_DIR = isDev
  ? path.join(__dirname, '..')
  : path.join(process.resourcesPath, 'engine');
const USER_DIR = app.getPath('userData');
const READY_TIMEOUT_MS = 30000;
const DEFAULT_PORT = 5087;
// 桌面配置标记：带此行的 .sitelens.yml 由壳维护，可安全刷新；
// 无标记（用户手写/仓库开发配置）则完全不碰。
const CONFIG_MARKER = '# generated by SiteLens desktop shell';

let engine = null;
let engineURL = '';
let restarts = [];
let onCrash = null; // 引擎意外退出的回调（主进程做自动重启/弹窗）

// log 输出落盘（userData/engine.log，1MB 截断），排障用。
function log(chunk) {
  try {
    const file = path.join(USER_DIR, 'engine.log');
    let prev = '';
    try {
      const st = fs.statSync(file);
      if (st.size > 1024 * 1024) prev = '';
      else prev = fs.readFileSync(file, 'utf8');
    } catch (_) { /* 首次无日志 */ }
    fs.writeFileSync(file, (prev + chunk).slice(-1024 * 1024));
  } catch (_) { /* 日志失败不影响主流程 */ }
}

// forward 把路径转成 YAML 安全形态（反斜杠在双引号/普通标量里都是坑）。
function forward(p) {
  return p.replace(/\\/g, '/');
}

// seedOnce 首启把安装包内置的可变情报种子复制到用户数据区
//（已存在则跳过：用户后续 update-* 的成果不被覆盖）。
function seedOnce() {
  const seeds = [
    ['data/nvd_cves.json.gz', 'data/nvd_cves.json.gz'],
    ['data/tpl_intel.json.gz', 'data/tpl_intel.json.gz'],
  ];
  for (const [src, dest] of seeds) {
    const from = path.join(ENGINE_DIR, src);
    const to = path.join(USER_DIR, dest);
    if (fs.existsSync(from) && !fs.existsSync(to)) {
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
    }
  }
  // 指纹规则目录整树按文件补缺（update-fp/update-ehole 会改写其中文件）
  const goSrc = path.join(ENGINE_DIR, 'data', 'go');
  if (fs.existsSync(goSrc)) {
    for (const name of fs.readdirSync(goSrc)) {
      const from = path.join(goSrc, name);
      const to = path.join(USER_DIR, 'data', 'go', name);
      if (fs.statSync(from).isFile() && !fs.existsSync(to)) {
        fs.mkdirSync(path.dirname(to), { recursive: true });
        fs.copyFileSync(from, to);
      }
    }
  }
  for (const dir of ['state', 'pools/nuclei', 'plugins', 'data/go']) {
    fs.mkdirSync(path.join(USER_DIR, dir), { recursive: true });
  }
}

// portOf 从既有配置里读监听端口；无配置/读不出返回 null。
function portOf(cfgPath) {
  try {
    const m = fs.readFileSync(cfgPath, 'utf8').match(/^\s*listen:\s*127\.0\.0\.1:(\d+)\s*$/m);
    return m ? Number(m[1]) : null;
  } catch (_) {
    return null;
  }
}

function portFree(port) {
  return new Promise((resolve) => {
    const srv = net.createServer();
    srv.once('error', () => resolve(false));
    srv.listen(port, '127.0.0.1', () => srv.close(() => resolve(true)));
  });
}

function freePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.listen(0, '127.0.0.1', () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
    srv.on('error', reject);
  });
}

// ensureConfig 保证桌面配置存在且端口可用，返回最终端口。
// 策略：默认 5087 固定端口（控制台地址跨启动稳定）；被占用才换
// 随机端口并持久化。配置带壳标记才允许刷新（见 CONFIG_MARKER）。
async function ensureConfig() {
  seedOnce();
  const cfgPath = path.join(ENGINE_DIR, '.sitelens.yml');
  let port = portOf(cfgPath);
  const marked = (() => {
    try {
      return fs.readFileSync(cfgPath, 'utf8').includes(CONFIG_MARKER);
    } catch (_) {
      return false;
    }
  })();
  if (port === null || !marked) {
    port = DEFAULT_PORT;
  }
  if (!(await portFree(port))) {
    port = await freePort();
  }
  // 路径全部正斜杠（YAML 反斜杠转义是已知坑）；引擎 CWD=ENGINE_DIR，
  // 未覆写的路径（intel_dump/ranges/wordlists/overrides）自然落在安装
  // 目录只读资产上。
  const yml = [
    CONFIG_MARKER,
    'web:',
    '  listen: 127.0.0.1:' + port,
    'store:',
    '  data_dir: ' + forward(path.join(USER_DIR, 'state')),
    'checks:',
    '  nuclei_dir: ' + forward(path.join(USER_DIR, 'pools', 'nuclei')),
    '  plugin_dir: ' + forward(path.join(USER_DIR, 'plugins')),
    'intel:',
    '  nvd_path: ' + forward(path.join(USER_DIR, 'data', 'nvd_cves.json.gz')),
    '  tpl_intel_path: ' + forward(path.join(USER_DIR, 'data', 'tpl_intel.json.gz')),
    '  technologies_path: ' + forward(path.join(USER_DIR, 'data', 'go', 'technologies.json')),
    '',
  ].join('\n');
  fs.writeFileSync(cfgPath, yml);
  return port;
}

// probe 一次就绪探测：引擎根路径返回任意响应即视为已监听。
function probe(url) {
  return new Promise((resolve) => {
    const req = http.get(url, { timeout: 1500 }, (res) => {
      res.resume();
      resolve(true);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
  });
}

async function waitReady(url) {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  while (Date.now() < deadline) {
    if (await probe(url)) return true;
    await new Promise((r) => setTimeout(r, 300));
  }
  return false;
}

// spawnEngine 拉起引擎。spawn 首参用纯字面量（相对引擎工作目录解析）：
// Windows 直接命中同目录二进制；POSIX 需要 ./ 前缀才会搜索当前目录。
function spawnEngine() {
  if (process.platform === 'win32') {
    engine = spawn('sitelens.exe', ['-config', '.sitelens.yml', 'serve'], {
      cwd: ENGINE_DIR, // 只读资产与桌面配置随引擎目录解析
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'], // stdout/stderr 都要接日志，不能 ignore
    });
  } else {
    engine = spawn('./sitelens', ['-config', '.sitelens.yml', 'serve'], {
      cwd: ENGINE_DIR,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  }
  engine.stdout.on('data', log);
  engine.stderr.on('data', log);
  engine.on('exit', (code) => {
    engine = null;
    if (onCrash) onCrash(code);
  });
}

// start 初始化布局、拉起引擎并等就绪；resolve 引擎根 URL。
async function start() {
  const exeName = process.platform === 'win32' ? 'sitelens.exe' : 'sitelens';
  if (!fs.existsSync(path.join(ENGINE_DIR, exeName))) {
    throw new Error('引擎程序缺失：' + ENGINE_DIR);
  }
  const port = await ensureConfig();
  engineURL = 'http://127.0.0.1:' + port;
  spawnEngine();
  if (!(await waitReady(engineURL))) {
    throw new Error('引擎在 ' + READY_TIMEOUT_MS / 1000 + ' 秒内未就绪（端口 ' + port + '）');
  }
  return engineURL;
}

// restart 崩溃自愈：重新拉起引擎（端口沿用配置），返回是否成功。
async function restart() {
  if (engine) return true;
  try {
    const port = portOf(path.join(ENGINE_DIR, '.sitelens.yml')) || DEFAULT_PORT;
    engineURL = 'http://127.0.0.1:' + port;
    spawnEngine();
    return await waitReady(engineURL);
  } catch (_) {
    return false;
  }
}

function stop() {
  if (engine) {
    try {
      engine.kill();
    } catch (_) { /* 已退出 */ }
    engine = null;
  }
}

module.exports = {
  ENGINE_DIR,
  USER_DIR,
  start,
  restart,
  stop,
  set onCrash(fn) {
    onCrash = fn;
  },
  get url() {
    return engineURL;
  },
};
