// 引擎子进程管理（供桌面壳 main.js 调用）。
//
// 职责：初始化用户数据布局 → 合并端口覆盖配置 → 拉起 Go 引擎单二进制 →
// 就绪探测 → 崩溃回调。
//
// 配置合并（P0 修正）：壳只管理「壳语义」键（监听端口 / 数据目录 /
// 资产路径），经 lib/yml-merge.js 原位合并进引擎的 .sitelens.yml——
// 用户在设置页保存的引擎配置（headless、爬取、api_token…）与注释、
// 未知键永远保留，壳重启不再抹掉它们。合并逻辑在 lib/ 里可独立单测。
//
// 子进程安全约定：spawn 首参为纯字面量（相对引擎工作目录解析），
// argv 全部内联字面量；不提供环境变量或配置选择可执行程序的通道。
//
// 退出协议：Windows 上无法向隐藏控制台子进程投递 CTRL+C，
// 停止采用 taskkill 树杀（/T 覆盖引擎拉起的浏览器驱动等孙进程）；
// 引擎的存储写入是 tmp+rename 原子语义，强杀不损坏历史数据。
const { app } = require('electron');
const { spawn } = require('child_process');
const fs = require('fs');
const http = require('http');
const net = require('net');
const path = require('path');
const merge = require('../lib/yml-merge.js');

const isDev = !app.isPackaged;
const ENGINE_DIR = isDev
  ? path.join(__dirname, '..')
  : path.join(process.resourcesPath, 'engine');
const READY_TIMEOUT_MS = 90000; // 冷启动需加载全量情报与模板索引，给足窗口
const DEFAULT_PORT = 5087;
const CONFIG_MARKER = '# generated by SiteLens desktop shell';
const CONFIG_NAME = '.sitelens.yml';

let engine = null;
let engineURL = '';
let started = false; // 就绪后为 true：崩溃回调只对「启动成功后的退出」触发
let onCrash = null;

// USER_DIR 延迟取（userData 需要应用名就绪）。
function USER_DIR() { return app.getPath('userData'); }

// underRoot 路径边界校验：目标必须落在 root 内（防拼接出逃）。
function underRoot(root, ...seg) {
  const base = path.resolve(root);
  const target = path.resolve(base, ...seg);
  if (target !== base && !target.startsWith(base + path.sep)) {
    throw new Error('路径越出数据根目录');
  }
  return target;
}

// log 输出落盘（userData/engine.log，1MB 截断），排障用。
function log(chunk) {
  try {
    const file = underRoot(app.getPath('userData'), 'engine.log');
    let prev = '';
    try {
      const st = fs.statSync(file);
      if (st.size > 1024 * 1024) prev = '';
      else prev = fs.readFileSync(file, 'utf8');
    } catch (_) { /* 首次无日志 */ }
    fs.writeFileSync(file, (prev + chunk).slice(-1024 * 1024));
  } catch (_) { /* 日志失败不影响主流程 */ }
}

// seedOnce 首启把安装包内置的可变情报种子复制到用户数据区
//（已存在则跳过：用户后续 update-* 的成果不被覆盖）。
function seedOnce() {
  seedGz('nvd_cves.json.gz');
  seedGz('tpl_intel.json.gz');
  const goSrc = path.join(ENGINE_DIR, 'data', 'go');
  if (fs.existsSync(goSrc)) {
    for (const name of fs.readdirSync(goSrc)) {
      const from = path.join(goSrc, name);
      const to = underRoot(USER_DIR(), 'data', 'go', name);
      if (fs.statSync(from).isFile() && !fs.existsSync(to)) {
        fs.mkdirSync(path.dirname(to), { recursive: true });
        fs.copyFileSync(from, to);
      }
    }
  }
  for (const dir of ['state', 'pools/nuclei', 'plugins', 'data/go']) {
    fs.mkdirSync(underRoot(USER_DIR(), dir), { recursive: true });
  }
}

// seedGz 复制单个 gz 种子（文件名常量，落在用户数据区 data/ 下）。
function seedGz(name) {
  const from = path.join(ENGINE_DIR, 'data', name);
  const to = underRoot(USER_DIR(), 'data', name);
  if (fs.existsSync(from) && !fs.existsSync(to)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

function freePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.listen(0, '127.0.0.1', () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
    srv.on('error', reject);
  });
}

function portFree(port) {
  return new Promise((resolve) => {
    const srv = net.createServer();
    srv.once('error', () => resolve(false));
    srv.listen(port, '127.0.0.1', () => srv.close(() => resolve(true)));
  });
}

// probe 一次就绪探测：引擎根路径返回任意响应即视为已监听。
function probe(url) {
  return new Promise((resolve) => {
    const req = http.get(url, { timeout: 1500 }, (res) => {
      res.resume();
      resolve(true);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
  });
}

// waitReady 轮询就绪；引擎提前退出立即返回（不傻等满超时）。
async function waitReady(timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (engine === null) return { ready: false, exited: true };
    if (await probe(engineURL)) return { ready: true };
    await new Promise((r) => setTimeout(r, 250));
  }
  return { ready: false, exited: engine === null };
}

// readDesktopConfig 读壳管理的配置文本；不存在返回 null。
function readDesktopConfig() {
  const cfgPath = path.join(ENGINE_DIR, CONFIG_NAME);
  try {
    const text = fs.readFileSync(cfgPath, 'utf8');
    return { text: text, marked: text.includes(CONFIG_MARKER) };
  } catch (_) {
    return null;
  }
}

// ensureConfig 保证桌面配置存在、受管键正确、端口可用；返回最终端口。
// 与旧实现的本质区别：受管键经 merge 原位更新，用户经设置页保存的
// 引擎配置（headless、爬取、api_token…）与注释、未知键全部保留。
// 未标记的存量配置（开发仓库的用户配置）完全不动，沿用其端口。
async function ensureConfig() {
  seedOnce();
  const cfgPath = path.join(ENGINE_DIR, CONFIG_NAME);
  const cur = readDesktopConfig();

  // 端口粘性 + 主机语义保留（桌面端审计修正）：
  // - 端口由壳偏好持久化（desktop-prefs.json），跨重启稳定
  // - 主机沿用配置原文（用户改绑 0.0.0.0 等予以保留，不悄悄回退）
  // - 回读失败降级必须有日志
  let usePort = 5087;
  let listenHost = '127.0.0.1';
  if (cur) {
    const prev = merge.readListenValue(cur.text);
    if (prev) {
      usePort = prev.port;
      listenHost = prev.host;
    } else {
      log('listen 端口回读失败（配置存在但格式不可解析），回退默认端口 ' + DEFAULT_PORT);
    }
  }
  if (!(await portFree(usePort))) {
    log('端口 ' + usePort + ' 被占用，改用随机空闲端口并写回配置');
    usePort = await freePort();
  }

  const managed = {
    web: { listen: listenHost + ':' + usePort },
    store: { data_dir: underRoot(USER_DIR(), 'state') },
    checks: {
      nuclei_dir: underRoot(USER_DIR(), 'pools', 'nuclei'),
      plugin_dir: underRoot(USER_DIR(), 'plugins')
    },
    intel: {
      nvd_path: underRoot(USER_DIR(), 'data', 'nvd_cves.json.gz'),
      tpl_intel_path: underRoot(USER_DIR(), 'data', 'tpl_intel.json.gz'),
      technologies_path: underRoot(USER_DIR(), 'data', 'go', 'technologies.json')
    }
  };
  const source = cur ? cur.text : CONFIG_MARKER + '\n';
  const merged = merge.mergeManaged(cur ? source : source, managed);
  if (merged !== cur?.text) fs.writeFileSync(cfgPath, merged);
  return usePort;
}

// spawnEngine 拉起引擎。spawn 首参为纯字面量（相对引擎工作目录解析）：
// Windows 直接命中同目录二进制；POSIX 需要 ./ 前缀才会搜索当前目录。
function spawnEngine() {
  if (process.platform === 'win32') {
    engine = spawn('sitelens.exe', ['-config', CONFIG_NAME, 'serve'], {
      cwd: ENGINE_DIR, // 只读资产与桌面配置随引擎目录解析
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'] // stdout/stderr 都要接日志，不能 ignore
    });
  } else {
    engine = spawn('./sitelens', ['-config', CONFIG_NAME, 'serve'], {
      cwd: ENGINE_DIR,
      stdio: ['ignore', 'pipe', 'pipe']
    });
  }
  engine.stdout.on('data', log);
  engine.stderr.on('data', log);
  engine.on('exit', (code) => {
    engine = null;
    if (started) {
      started = false;
      if (onCrash) onCrash(code);
    }
  });
}

// start 初始化布局、拉起引擎并等就绪；resolve 引擎根 URL。
// 端口被抢注（TOCTOU）时引擎绑定失败即退，这里最多重试 3 次
//（每次重选空闲端口重写配置）。
async function start() {
  const exeName = process.platform === 'win32' ? 'sitelens.exe' : 'sitelens';
  if (!fs.existsSync(path.join(ENGINE_DIR, exeName))) {
    throw new Error('引擎程序缺失：' + ENGINE_DIR);
  }
  let lastErr = new Error('引擎启动失败');
  for (let attempt = 1; attempt <= 3; attempt++) {
    const port = await ensureConfig();
    engineURL = 'http://127.0.0.1:' + port;
    spawnEngine();
    const rr = await waitReady(READY_TIMEOUT_MS);
    if (rr.ready) {
      started = true;
      return engineURL;
    }
    lastErr = rr.exited
      ? new Error('引擎启动即退出（退出码 ' + rr.code + '，常见原因：端口被占用）')
      : new Error('引擎在 ' + READY_TIMEOUT_MS / 1000 + ' 秒内未就绪（端口 ' + port + '）');
    await stop();
  }
  throw lastErr;
}

// restart 崩溃自愈入口：与 start 同路径（配置已就位，直接拉起）。
async function restart() {
  if (engine) return engineURL;
  return start();
}

// stop 尽可能干净的停止：Windows 用 taskkill 树杀（/T 覆盖引擎拉起的
// 浏览器驱动等孙进程），POSIX 先 SIGTERM 超时 SIGKILL；等待真正退出。
function stop() {
  started = false;
  if (!engine) return Promise.resolve();
  const child = engine;
  engine = null;
  return new Promise((resolve) => {
    let done = false;
    const finish = () => { if (!done) { done = true; resolve(); } };
    child.once('exit', finish);
    if (process.platform === 'win32') {
      const tk = spawn('taskkill', ['/pid', String(child.pid), '/T'], {
        windowsHide: true, stdio: 'ignore'
      });
      tk.once('exit', () => {
        // 温和树杀对控制台程序常无效，随后强制树杀
        try {
          spawn('taskkill', ['/pid', String(child.pid), '/T', '/F'], {
            windowsHide: true, stdio: 'ignore'
          }).once('exit', () => setTimeout(finish, 200));
        } catch (_) { finish(); }
      });
      setTimeout(finish, 8000); // 兜底
    } else {
      child.kill('SIGTERM');
      setTimeout(() => { try { child.kill('SIGKILL'); } catch (_) {} }, 3000);
      setTimeout(finish, 6000);
    }
  });
}

module.exports = {
  ENGINE_DIR,
  start,
  restart,
  stop,
  alive: function () { return !!engine; },
  set onCrash(fn) { onCrash = fn; },
  get url() { return engineURL; }
};
